#!/usr/bin/env python3
"""Set the Boswas OS wordmarks in Orbitron, the brand typeface, as outlines.

The wordmarks are converted to SVG paths, so artwork renders identically
everywhere (Qt cannot use <text> with a font it does not have, and GRUB and
the Debian Installer get pre-rendered images anyway).

  ../fonts/orbitron/static/Orbitron-SemiBold.ttf   (SIL OFL 1.1)

Outputs (written to desktop/branding/, committed to the repository):

  wordmark-boswas-os.svg   BOSWAS OS
  wordmark-boswas.svg      BOSWAS
  wordmark-os.svg          OS

All outputs are white (#FFFFFF) on a transparent background, cropped to the
ink (cap height top to baseline), and are recoloured with data-fill (see
build/scripts/inline-svg.py).

Requires: python3, python3-fonttools.
Run from the repository root:  python3 desktop/branding/tools/build_wordmarks.py
"""

from __future__ import annotations

import sys
from pathlib import Path

from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

BRANDING = Path(__file__).resolve().parents[1]
FONT = BRANDING.parent / "fonts" / "orbitron" / "static" / "Orbitron-SemiBold.ttf"
TRACKING = 0.12        # letter spacing, in em
WORDMARKS = {"wordmark-boswas-os.svg": "BOSWAS OS", "wordmark-boswas.svg": "BOSWAS", "wordmark-os.svg": "OS"}


def outline(font: TTFont, text: str) -> tuple[str, tuple[float, float, float, float]]:
    glyphs, cmap = font.getGlyphSet(), font.getBestCmap()
    upem = font["head"].unitsPerEm
    pen, bounds = SVGPathPen(glyphs), BoundsPen(glyphs)
    x = 0.0
    for index, char in enumerate(text):
        name = cmap[ord(char)]
        if char != " ":
            # Font units are y-up; SVG is y-down.
            glyphs[name].draw(TransformPen(pen, (1, 0, 0, -1, x, 0)))
            glyphs[name].draw(TransformPen(bounds, (1, 0, 0, -1, x, 0)))
        x += glyphs[name].width + (TRACKING * upem if index < len(text) - 1 else 0)
    return pen.getCommands(), bounds.bounds


def main() -> int:
    font = TTFont(FONT)
    family = font["name"].getDebugName(16) or font["name"].getDebugName(1).split()[0]
    style = font["name"].getDebugName(17) or font["name"].getDebugName(2)
    for file_name, text in WORDMARKS.items():
        d, (x0, y0, x1, y1) = outline(font, text)
        w, h = x1 - x0, y1 - y0
        svg = (f'<svg xmlns="http://www.w3.org/2000/svg" width="{w:.0f}" height="{h:.0f}" '
               f'viewBox="{x0:.1f} {y0:.1f} {w:.1f} {h:.1f}">\n'
               f'  <title>{text} ({family} {style}, tracking {TRACKING} em)</title>\n'
               f'  <!-- Generated by desktop/branding/tools/build_wordmarks.py; do not edit by hand. -->\n'
               f'  <path fill="#FFFFFF" d="{d}"/>\n'
               f'</svg>\n')
        (BRANDING / file_name).write_text(svg)
        print(f"{file_name}: {text!r} {w:.0f} x {h:.0f} font units")
    return 0


if __name__ == "__main__":
    sys.exit(main())
