#!/usr/bin/env python3
"""Generate the Boswas OS visual presets from presets.json.

presets.json is the single source of truth. This tool turns it into:

  color-schemes/Boswas<Label>.colors                   KDE colour schemes
  konsole/Boswas<Label>.colorscheme                     Konsole colour schemes
  konsole/Boswas <Label>.profile                        Konsole profiles
  look-and-feel/com.boswas.<id>/...                     Plasma Global Themes
  wallpapers/Boswas-<Label>/{metadata.json,light.svg,dark.svg,lock.svg}
  wallpapers/Boswas/metadata.json                       the default wallpaper (Horizon)
  previews/<id>.svg                                     schematic desktop previews

All of these are generated: do not edit them by hand, edit presets.json (or
this tool) and run it again. The SVG sources reference the brand assets in
desktop/branding with <image href=...>; install.sh inlines them with
build/scripts/inline-svg.py and renders the PNGs with rsvg-convert.

Usage:
  build_presets.py                regenerate desktop/presets in place
  build_presets.py --output DIR   write the generated tree to DIR instead
  build_presets.py --check        exit 1 if the committed files are out of date

Python 3 standard library only.
"""

from __future__ import annotations

import argparse
import json
import math
import sys
from pathlib import Path

PRESETS_DIR = Path(__file__).resolve().parent.parent
GENERATED_DIRS = ("color-schemes", "konsole", "look-and-feel", "wallpapers", "previews")
NOTICE = "Generated by desktop/presets/tools/build_presets.py from presets.json; do not edit by hand."

# Canvas of every wallpaper source (rendered at 3840x2160).
W, H = 3840, 2160

# Geometry of the Boswas OS mark (desktop/branding/boswas-os-mark*.svg,
# viewBox 527 x 655), measured on the traced artwork: the dot and the ring
# share one centre; the stem is the blade on the left.
MARK_W, MARK_H = 527.0, 655.0
MARK_CX, MARK_CY = 270.0, 389.5          # centre of the dot and of the ring
MARK_RING = 250.0                         # outer radius of the ring
MARK_STEM = (14.0, 14.0, 144.0, 451.0)    # stem bounding box (x, y, w, h)

# Shared desktop content (contract with the Boswas Launcher and Control Center).
LAUNCHER_PLUGIN = "com.boswas.launcher"
LAUNCHER_ICON = "boswas-logo"
FAVORITES = [
    "com.boswas.ControlCenter.desktop",
    "org.kde.dolphin.desktop",
    "org.kde.konsole.desktop",
    "firefox-esr.desktop",
    "com.boswas.CompatibilityManager.desktop",
    "org.kde.kcalc.desktop",
]
SYSTEM_APPLICATIONS = [
    "com.boswas.ControlCenter.desktop",
    "com.boswas.SecurityCenter.desktop",
    "org.kde.kinfocenter.desktop",
]
PINNED_LAUNCHERS = [
    "applications:com.boswas.ControlCenter.desktop",
    "applications:org.kde.dolphin.desktop",
    "applications:org.kde.konsole.desktop",
    "applications:firefox-esr.desktop",
    "applications:com.boswas.CompatibilityManager.desktop",
]
SPLASH_THEME = "com.boswas.splash"
TERMINAL_FONT = "Hack,11"
TERMINAL_COMMAND = "/usr/bin/bash --rcfile /usr/share/boswas/terminal/bashrc"
AUTHOR = "Boswas Group"
LICENSE = "LicenseRef-Boswas-Internal"


# --------------------------------------------------------------------------
# Colour helpers
# --------------------------------------------------------------------------

def rgb(value: str) -> tuple[int, int, int]:
    value = value.lstrip("#")
    return int(value[0:2], 16), int(value[2:4], 16), int(value[4:6], 16)


def hexcolor(channels) -> str:
    return "#%02X%02X%02X" % tuple(max(0, min(255, int(round(c)))) for c in channels)


def triplet(value: str) -> str:
    return "%d,%d,%d" % rgb(value)


def mix(a: str, b: str, t: float) -> str:
    """Blend a towards b (t = 0 gives a, t = 1 gives b)."""
    return hexcolor(x + (y - x) * t for x, y in zip(rgb(a), rgb(b)))


def luminance(value: str) -> float:
    def linear(channel: int) -> float:
        c = channel / 255.0
        return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4

    r, g, b = (linear(c) for c in rgb(value))
    return 0.2126 * r + 0.7152 * g + 0.0722 * b


def contrast(a: str, b: str) -> float:
    high, low = sorted((luminance(a), luminance(b)), reverse=True)
    return (high + 0.05) / (low + 0.05)


def is_dark(value: str) -> bool:
    return contrast(value, "#FFFFFF") > contrast(value, "#000000")


def readable(color: str, background: str, ratio: float = 4.5) -> str:
    """Move color towards white (dark background) or black (light background)
    until it reaches the contrast ratio against background."""
    target = "#FFFFFF" if is_dark(background) else "#000000"
    out, step = color, 0
    while contrast(out, background) < ratio and step < 20:
        step += 1
        out = mix(color, target, step / 20.0)
    return out


# --------------------------------------------------------------------------
# Small formatting helpers
# --------------------------------------------------------------------------

def num(value: float) -> str:
    text = f"{value:.2f}".rstrip("0").rstrip(".")
    return "0" if text in ("-0", "") else text


def ini(sections: list[tuple[str, list[tuple[str, str]]]], comment: str = "") -> str:
    lines = [f"# {line}" if line else "#" for line in comment.splitlines()] if comment else []
    if lines:
        lines.append("")
    for name, entries in sections:
        lines.append(f"[{name}]")
        lines.extend(f"{key}={value}" for key, value in entries)
        lines.append("")
    return "\n".join(lines)


def dump_json(data) -> str:
    return json.dumps(data, indent=4, ensure_ascii=True) + "\n"


# --------------------------------------------------------------------------
# Names derived from a preset
# --------------------------------------------------------------------------

def scheme_name(p: dict) -> str:
    return "Boswas" + p["label"]


def wallpaper_name(p: dict) -> str:
    return "Boswas-" + p["label"]


def lnf_id(p: dict) -> str:
    return "com.boswas." + p["id"]


def profile_name(p: dict) -> str:
    return f"Boswas {p['label']}.profile"


def primary(p: dict) -> str:
    """The wallpaper variant shown with the preset's own colour scheme."""
    return "dark" if p["variant"] == "dark" else "light"


# --------------------------------------------------------------------------
# KDE colour scheme
# --------------------------------------------------------------------------

COLOR_KEYS = (
    "BackgroundAlternate", "BackgroundNormal", "DecorationFocus", "DecorationHover",
    "ForegroundActive", "ForegroundInactive", "ForegroundLink", "ForegroundNegative",
    "ForegroundNeutral", "ForegroundNormal", "ForegroundPositive", "ForegroundVisited",
)

COLOR_GROUPS = (
    "Colors:Button", "Colors:Complementary", "Colors:Header", "Colors:Header][Inactive",
    "Colors:Selection", "Colors:Tooltip", "Colors:View", "Colors:Window",
)


def color_groups(p: dict) -> dict[str, dict[str, str]]:
    c = p["palette"]

    def group(bg: str, alt: str, text: str | None = None, muted: str | None = None,
              strict: bool = False) -> dict[str, str]:
        text = text or c["text"]
        muted = muted or c["muted"]
        values = {
            "BackgroundAlternate": alt,
            "BackgroundNormal": bg,
            "DecorationFocus": c["accent"],
            "DecorationHover": c["accent_hover"],
            "ForegroundActive": c["accent_text"],
            "ForegroundInactive": muted,
            "ForegroundLink": c["link"],
            "ForegroundNegative": c["negative"],
            "ForegroundNeutral": c["neutral"],
            "ForegroundNormal": text,
            "ForegroundPositive": c["positive"],
            "ForegroundVisited": c["visited"],
        }
        if strict:
            # A background of the opposite lightness (Complementary on a light
            # scheme): keep every foreground readable on it.
            for key in ("ForegroundActive", "ForegroundLink", "ForegroundNegative",
                        "ForegroundNeutral", "ForegroundPositive", "ForegroundVisited"):
                values[key] = readable(values[key], bg)
            for key in ("DecorationFocus", "DecorationHover"):
                values[key] = readable(values[key], bg, 3.0)
        return values

    selection = group(c["selection"], c["selection_alt"], c["selection_text"],
                      mix(c["selection_text"], c["selection"], 0.3), strict=True)
    selection["DecorationFocus"] = c["accent"]
    selection["DecorationHover"] = c["accent_hover"]
    selection["ForegroundActive"] = c["selection_text"]

    return {
        "Colors:Button": group(c["button"], c["button_alt"]),
        "Colors:Complementary": group(c["complementary"], c["complementary_alt"],
                                      c["complementary_text"], c["complementary_muted"],
                                      strict=is_dark(c["complementary"]) != is_dark(c["window"])),
        "Colors:Header": group(c["header"], c["header_alt"]),
        "Colors:Header][Inactive": group(c["header_inactive"], c["header_alt"]),
        "Colors:Selection": selection,
        "Colors:Tooltip": group(c["tooltip"], c["window_alt"]),
        "Colors:View": group(c["view"], c["view_alt"]),
        "Colors:Window": group(c["window"], c["window_alt"]),
    }


def colors_file(p: dict) -> str:
    c = p["palette"]
    sections: list[tuple[str, list[tuple[str, str]]]] = [
        ("ColorEffects:Disabled", [
            ("Color", "56,56,56"), ("ColorAmount", "0"), ("ColorEffect", "0"),
            ("ContrastAmount", "0.65"), ("ContrastEffect", "1"),
            ("IntensityAmount", "0.1"), ("IntensityEffect", "2"),
        ]),
        ("ColorEffects:Inactive", [
            ("ChangeSelectionColor", "true"), ("Color", "112,111,110"), ("ColorAmount", "0.025"),
            ("ColorEffect", "2"), ("ContrastAmount", "0.1"), ("ContrastEffect", "2"),
            ("Enable", "false"), ("IntensityAmount", "0"), ("IntensityEffect", "0"),
        ]),
    ]
    for name, values in color_groups(p).items():
        sections.append((name, [(key, triplet(values[key])) for key in COLOR_KEYS]))
    sections.append(("General", [
        ("ColorScheme", scheme_name(p)),
        ("Name", p["name"]),
        ("shadeSortColumn", "true"),
    ]))
    sections.append(("KDE", [("contrast", "4")]))
    dark = p["variant"] == "dark"
    sections.append(("WM", [
        ("activeBackground", triplet(c["header"])),
        ("activeBlend", triplet(c["text"] if dark else c["header"])),
        ("activeForeground", triplet(c["text"])),
        ("inactiveBackground", triplet(c["header_inactive"])),
        ("inactiveBlend", triplet(c["muted"] if dark else c["header_inactive"])),
        ("inactiveForeground", triplet(c["muted"])),
    ]))
    return ini(sections, f"{p['name']} colour scheme ({p['variant']}).\n{NOTICE}")


# --------------------------------------------------------------------------
# Konsole
# --------------------------------------------------------------------------

def konsole_scheme(p: dict) -> str:
    t = p["terminal"]
    bg, fg, colors = t["background"], t["foreground"], t["colors"]
    toward = "#FFFFFF" if is_dark(bg) else "#000000"
    sections = [
        ("Background", [("Color", triplet(bg))]),
        ("BackgroundFaint", [("Color", triplet(bg))]),
        ("BackgroundIntense", [("Color", triplet(mix(bg, toward, 0.06)))]),
    ]
    for i in range(8):
        normal, intense = colors[i], colors[i + 8]
        sections.append((f"Color{i}", [("Color", triplet(normal))]))
        sections.append((f"Color{i}Faint", [("Color", triplet(mix(normal, bg, 0.4)))]))
        sections.append((f"Color{i}Intense", [("Color", triplet(intense))]))
    sections += [
        ("Foreground", [("Color", triplet(fg))]),
        ("ForegroundFaint", [("Color", triplet(mix(fg, bg, 0.35)))]),
        ("ForegroundIntense", [("Color", triplet(mix(fg, toward, 0.6)))]),
        ("General", [
            ("Blur", "false"),
            ("ColorRandomization", "false"),
            ("Description", p["name"]),
            ("Opacity", "1"),
            ("Wallpaper", ""),
        ]),
    ]
    return ini(sections, f"{p['name']} Konsole colour scheme.\n{NOTICE}")


def konsole_profile(p: dict) -> str:
    sections = [
        ("Appearance", [("ColorScheme", scheme_name(p)), ("Font", TERMINAL_FONT)]),
        ("General", [
            ("Command", TERMINAL_COMMAND),
            ("Name", p["name"]),
            ("Parent", "FALLBACK/"),
        ]),
        ("Scrolling", [("HistorySize", "10000")]),
        ("Terminal Features", [("BlinkingCursorEnabled", "false")]),
    ]
    return ini(sections, f"{p['name']} Konsole profile.\n{NOTICE}")


# --------------------------------------------------------------------------
# Plasma Global Theme (look-and-feel package)
# --------------------------------------------------------------------------

def lnf_metadata(p: dict) -> str:
    return dump_json({
        "KPackageStructure": "Plasma/LookAndFeel",
        "KPlugin": {
            "Authors": [{"Name": AUTHOR}],
            "Category": "",
            "Description": p["description"],
            "Id": lnf_id(p),
            "License": LICENSE,
            "Name": p["name"],
            "Website": "",
        },
    })


def lnf_defaults(p: dict) -> str:
    sections = [
        ("kdeglobals][KDE", [("widgetStyle", "Breeze")]),
        ("kdeglobals][General", [("ColorScheme", scheme_name(p))]),
        ("kdeglobals][Icons", [("Theme", p["icon_theme"])]),
        ("plasmarc][Theme", [("name", p["plasma_style"])]),
        ("Wallpaper", [("Image", wallpaper_name(p))]),
        ("kcminputrc][Mouse", [("cursorTheme", "breeze_cursors")]),
        ("kwinrc][org.kde.kdecoration2", [("library", "org.kde.breeze"), ("theme", "Breeze")]),
        ("KSplash", [("Theme", SPLASH_THEME)]),
        ("ksplashrc][KSplash", [("Theme", SPLASH_THEME)]),
    ]
    return ini(sections)


LAYOUT_TEMPLATE = """\
// %(name)s: Plasma desktop layout.
// %(notice)s
//
// Plasma runs this script when a user first logs in with this Global Theme,
// and when the theme is applied together with its desktop layout (Global
// Theme settings: "Desktop and window layout"; `boswas-preset apply %(id)s
// --layout`). It starts from KDE's stock default panel (launcher, pager, task
// manager, system tray, clock) so Plasma upgrades keep working, then:
//   * replaces Kickoff with the Boswas Launcher at the same position (or
//     keeps Kickoff, with the same settings, if the Boswas Launcher is not
//     installed),
//   * pins the Boswas applications in the task manager,
//   * applies the panel style: %(style_doc)s.
// The wallpaper is left unset: Plasma then shows the Global Theme's default
// wallpaper ([Wallpaper] Image in the theme's defaults file).

var BOSWAS_LAUNCHER = "%(launcher)s";
var LAUNCHER_ICON = "%(icon)s";
var FAVORITES = %(favorites)s;
var SYSTEM_APPLICATIONS = %(system_applications)s;
var PINNED_LAUNCHERS = %(pinned)s;
var TASK_MANAGER = "%(task_manager)s";
var PANEL_FLOATING = %(floating)s;
var PANEL_FULL_WIDTH = %(full_width)s;

loadTemplate("org.kde.plasma.desktop.defaultPanel");

var desktopsArray = desktopsForActivity(currentActivity());
for (var j = 0; j < desktopsArray.length; j++) {
    desktopsArray[j].wallpaperPlugin = "org.kde.image";
}

function writeGeneral(widget, key, value) {
    widget.currentConfigGroup = ["General"];
    widget.writeConfig(key, value);
}

function configureLauncher(widget) {
    writeGeneral(widget, "icon", LAUNCHER_ICON);
    writeGeneral(widget, "favorites", FAVORITES);
    writeGeneral(widget, "systemApplications", SYSTEM_APPLICATIONS);
}

function configureTasks(widget) {
    writeGeneral(widget, "launchers", PINNED_LAUNCHERS);
}

// Replaces `widget` by a new widget of type `plugin` in the same slot of
// `order` (the panel's widget ids, in panel order). Returns the widget that
// ends up in the panel.
function replaceWidget(panel, order, widget, plugin) {
    var replacement = panel.addWidget(plugin);
    if (!replacement) {
        return widget;
    }
    var index = order.indexOf(widget.id);
    widget.remove();
    if (index >= 0) {
        order[index] = replacement.id;
    } else {
        order.push(replacement.id);
    }
    return replacement;
}

var haveBoswasLauncher = knownWidgetTypes.indexOf(BOSWAS_LAUNCHER) >= 0;
var allPanels = panels();
for (var i = 0; i < allPanels.length; i++) {
    var panel = allPanels[i];
    var ids = panel.widgetIds;
    var order = [];
    for (var k = 0; k < ids.length; k++) {
        order.push(ids[k]);
    }
    var reordered = false;

    var kickoffs = panel.widgets("org.kde.plasma.kickoff");
    for (var m = 0; m < kickoffs.length; m++) {
        var launcher = kickoffs[m];
        if (haveBoswasLauncher) {
            launcher = replaceWidget(panel, order, launcher, BOSWAS_LAUNCHER);
            reordered = true;
        }
        configureLauncher(launcher);
    }

    var taskManagers = panel.widgets("org.kde.plasma.icontasks");
    for (var n = 0; n < taskManagers.length; n++) {
        var tasks = taskManagers[n];
        if (TASK_MANAGER != "org.kde.plasma.icontasks") {
            tasks = replaceWidget(panel, order, tasks, TASK_MANAGER);
            reordered = true;
        }
        configureTasks(tasks);
    }

    if (reordered) {
        // Read by the panel when it is created, after this script has run.
        panel.currentConfigGroup = ["General"];
        panel.writeConfig("AppletOrder", order.join(";"));
    }

    panel.floating = PANEL_FLOATING;
    if (PANEL_FULL_WIDTH) {
        panel.lengthMode = "fill";
        panel.height = 2 * Math.floor(gridUnit * 2.25 / 2);
    }
}
"""


def layout_js(p: dict) -> str:
    panel = p["panel"]
    full = panel["style"] == "full-width"
    style_doc = ("full-width, non-floating panel with a labelled task manager" if full
                 else "floating panel with an icon-only task manager")
    return LAYOUT_TEMPLATE % {
        "name": p["name"],
        "notice": NOTICE,
        "id": p["id"],
        "style_doc": style_doc,
        "launcher": LAUNCHER_PLUGIN,
        "icon": LAUNCHER_ICON,
        "favorites": json.dumps(FAVORITES),
        "system_applications": json.dumps(SYSTEM_APPLICATIONS),
        "pinned": json.dumps(PINNED_LAUNCHERS),
        "task_manager": panel["task_manager"],
        "floating": "false" if full else "true",
        "full_width": "true" if full else "false",
    }


# --------------------------------------------------------------------------
# SVG building blocks
# --------------------------------------------------------------------------

class Svg:
    """A tiny SVG writer. Every id is prefixed so that documents can be nested
    (previews include the wallpaper) without clashes."""

    def __init__(self, prefix: str, width: int, height: int, title: str):
        self.prefix = prefix
        self.width, self.height = width, height
        self.title = title
        self.defs: list[str] = []
        self.body: list[str] = []
        self.count = 0

    def new_id(self, name: str) -> str:
        self.count += 1
        return f"{self.prefix}-{name}{self.count}"

    def add(self, element: str) -> None:
        self.body.append(element)

    def define(self, element: str) -> None:
        self.defs.append(element)

    def render(self) -> str:
        out = [
            f'<svg xmlns="http://www.w3.org/2000/svg" width="{self.width}" height="{self.height}" '
            f'viewBox="0 0 {self.width} {self.height}">',
            f"  <title>{self.title}</title>",
            f"  <!-- {NOTICE} -->",
        ]
        if self.defs:
            out.append("  <defs>")
            out.extend(f"    {d}" for d in self.defs)
            out.append("  </defs>")
        out.extend(f"  {b}" for b in self.body)
        out.append("</svg>")
        return "\n".join(out) + "\n"

    # Paint servers and filters ------------------------------------------

    def linear(self, stops, x1, y1, x2, y2) -> str:
        gid = self.new_id("lin")
        self.define(
            f'<linearGradient id="{gid}" gradientUnits="userSpaceOnUse" x1="{num(x1)}" y1="{num(y1)}" '
            f'x2="{num(x2)}" y2="{num(y2)}">{_stops(stops)}</linearGradient>')
        return f"url(#{gid})"

    def radial(self, stops, cx, cy, r, sx: float = 1.0, sy: float = 1.0) -> str:
        """Radial gradient; sx/sy stretch it into an ellipse around (cx, cy)."""
        gid = self.new_id("rad")
        transform = ""
        if sx != 1.0 or sy != 1.0:
            transform = (f' gradientTransform="translate({num(cx)} {num(cy)}) scale({num(sx)} {num(sy)}) '
                         f'translate({num(-cx)} {num(-cy)})"')
        self.define(
            f'<radialGradient id="{gid}" gradientUnits="userSpaceOnUse" cx="{num(cx)}" cy="{num(cy)}" '
            f'r="{num(r)}"{transform}>{_stops(stops)}</radialGradient>')
        return f"url(#{gid})"

    def blur(self, deviation: float) -> str:
        fid = self.new_id("blur")
        m = deviation * 4
        self.define(
            f'<filter id="{fid}" filterUnits="userSpaceOnUse" x="{num(-m)}" y="{num(-m)}" '
            f'width="{num(self.width + 2 * m)}" height="{num(self.height + 2 * m)}">'
            f'<feGaussianBlur stdDeviation="{num(deviation)}"/></filter>')
        return f"url(#{fid})"


def _stops(stops) -> str:
    out = []
    for stop in stops:
        offset, color = stop[0], stop[1]
        opacity = stop[2] if len(stop) > 2 else 1.0
        extra = "" if opacity >= 1.0 else f' stop-opacity="{num(opacity)}"'
        out.append(f'<stop offset="{num(offset)}" stop-color="{color}"{extra}/>')
    return "".join(out)


def polar(cx: float, cy: float, r: float, angle: float) -> tuple[float, float]:
    a = math.radians(angle)
    return cx + r * math.cos(a), cy + r * math.sin(a)


def arc_path(cx: float, cy: float, r: float, start: float, end: float) -> str:
    """Clockwise arc (screen coordinates, angles in degrees, 0 = east)."""
    x0, y0 = polar(cx, cy, r, start)
    x1, y1 = polar(cx, cy, r, end)
    large = 1 if (end - start) % 360 > 180 else 0
    return f"M{num(x0)} {num(y0)}A{num(r)} {num(r)} 0 {large} 1 {num(x1)} {num(y1)}"


def blade_path(x: float, y: float, w: float, h: float) -> str:
    """The stem of the mark: square top-left and bottom-right corners, the
    other two rounded into quarter ellipses."""
    top, bottom = 0.28 * h, 0.32 * h
    return (f"M{num(x)} {num(y)}A{num(w)} {num(top)} 0 0 1 {num(x + w)} {num(y + top)}"
            f"L{num(x + w)} {num(y + h)}A{num(w)} {num(bottom)} 0 0 1 {num(x)} {num(y + h - bottom)}Z")


def stem_box(cx: float, cy: float, ring_radius: float) -> tuple[float, float, float, float]:
    """Where the stem sits when the mark's ring has radius ring_radius around (cx, cy)."""
    s = ring_radius / MARK_RING
    x, y, w, h = MARK_STEM
    return cx + (x - MARK_CX) * s, cy + (y - MARK_CY) * s, w * s, h * s


class Rng:
    """Deterministic pseudo-random numbers (LCG), so sources are reproducible."""

    def __init__(self, seed: str):
        self.state = sum((i + 1) * ord(ch) for i, ch in enumerate(seed)) or 1

    def next(self) -> float:
        self.state = (1103515245 * self.state + 12345) % 2147483648
        return self.state / 2147483648.0

    def uniform(self, a: float, b: float) -> float:
        return a + (b - a) * self.next()


# --------------------------------------------------------------------------
# Wallpapers
# --------------------------------------------------------------------------
#
# Every wallpaper is built from the geometry of the Boswas OS mark:
#   * the orbit: rings concentric with the mark's ring, drawn around a focus,
#   * the trail: an arc on one ring that ends in the dot (a satellite),
#   * the blade: the stem of the mark, as a soft beam or glass plane,
#   * the mark itself at the focus, faint (it never dominates).
# The motif (horizon, aurora, waves...) changes the mood; the accent colour,
# the darkness and the motif are the only things that differ between presets.

BRANDING = "../../../branding"


def _mark(svg: Svg, cx: float, cy: float, height: float, fill: str, opacity: float,
          branding: str = BRANDING) -> None:
    width = height * MARK_W / MARK_H
    x = cx - MARK_CX / MARK_W * width
    y = cy - MARK_CY / MARK_H * height
    if fill == "colour":
        ref = f'href="{branding}/boswas-os-mark.svg"'
    else:
        ref = f'href="{branding}/boswas-os-mark-mono.svg" data-fill="{fill}"'
    svg.add(f'<image x="{num(x)}" y="{num(y)}" width="{num(width)}" height="{num(height)}" '
            f'{ref} opacity="{num(opacity)}"/>')


def _base(svg: Svg, v: dict, vertical: bool = False) -> None:
    c0, c1, c2 = v["base"]
    if vertical:
        fill = svg.linear([(0, c0), (0.55, c1), (1, c2)], 0, 0, 0, H)
    else:
        fill = svg.linear([(0, c0), (0.55, c1), (1, c2)], 0, 0, W, H)
    svg.add(f'<rect width="{W}" height="{H}" fill="{fill}"/>')


def _glows(svg: Svg, v: dict, fx: float, fy: float, scale: float = 1.0) -> None:
    if v["glow_opacity"] > 0:
        fill = svg.radial([(0, v["glow"], v["glow_opacity"]),
                           (0.5, v["glow"], v["glow_opacity"] * 0.3),
                           (1, v["glow"], 0)], fx, fy, 1500 * scale)
        svg.add(f'<rect width="{W}" height="{H}" fill="{fill}"/>')
    if v["ambient_opacity"] > 0:
        fill = svg.radial([(0, v["ambient"], v["ambient_opacity"]), (1, v["ambient"], 0)],
                          420, H + 60, 1700)
        svg.add(f'<rect width="{W}" height="{H}" fill="{fill}"/>')


def _orbit(svg: Svg, v: dict, fx: float, fy: float, r0: float, count: int = 5,
           ratio: float = 1.42, first: float = 1.55, width: float = 3.0) -> list[float]:
    radii = [r0 * first * ratio ** i for i in range(count)]
    parts = []
    for i, r in enumerate(radii):
        opacity = v["ring_opacity"] * max(0.25, 1.0 - 0.18 * i)
        parts.append(f'<circle cx="{num(fx)}" cy="{num(fy)}" r="{num(r)}" '
                     f'stroke-opacity="{num(opacity)}" stroke-width="{num(width)}"/>')
    svg.add(f'<g fill="none" stroke="{v["ring"]}">' + "".join(parts) + "</g>")
    return radii


def _trail(svg: Svg, v: dict, fx: float, fy: float, r: float, start: float, end: float,
           width: float = 6.0, dot: float = 17.0, strength: float = 1.0, light: bool = False) -> None:
    """An arc on a ring of the orbit. With a dot, it is a comet trail ending in
    the dot of the mark; without, a short highlight fading out at both ends."""
    x0, y0 = polar(fx, fy, r, start)
    x1, y1 = polar(fx, fy, r, end)
    if dot > 0:
        stops = [(0, v["accent"], 0), (0.7, v["accent"], 0.55 * strength), (1, v["accent_hi"], 0.95 * strength)]
    else:
        stops = [(0, v["accent"], 0), (0.5, v["accent_hi"], 0.8 * strength), (1, v["accent"], 0)]
    stroke = svg.linear(stops, x0, y0, x1, y1)
    svg.add(f'<path d="{arc_path(fx, fy, r, start, end)}" fill="none" stroke="{stroke}" '
            f'stroke-width="{num(width)}" stroke-linecap="round"/>')
    if dot > 0:
        # A glow around the dot on dark artwork; on light artwork a dark glow
        # would read as a smudge, so the halo is white there.
        halo_color = "#FFFFFF" if light else v["accent_hi"]
        halo = svg.radial([(0, halo_color, (0.7 if light else 0.45) * strength), (1, halo_color, 0)],
                          x1, y1, dot * 7)
        svg.add(f'<circle cx="{num(x1)}" cy="{num(y1)}" r="{num(dot * 7)}" fill="{halo}"/>')
        svg.add(f'<circle cx="{num(x1)}" cy="{num(y1)}" r="{num(dot)}" fill="{v["accent_hi"]}" '
                f'fill-opacity="{num(min(1.0, strength))}"/>')


def _blade(svg: Svg, box, color: str, top: float, bottom: float, edge: float = 0.0,
           soft: float = 0.0, dashed: bool = False, edge_color: str | None = None) -> None:
    """The stem of the mark at large scale: a soft glass plane or light shaft
    (fill), with an optional fine edge that fades out downwards."""
    x, y, w, h = box
    y = max(y, 70.0)   # keep the blade's square top corner in view
    d = blade_path(x, y, w, h)
    if top > 0 or bottom > 0:
        fill = svg.linear([(0, color, top), (1, color, bottom)], x, y, x + w * 0.3, y + h)
        filt = f' filter="{svg.blur(soft)}"' if soft else ""
        svg.add(f'<path d="{d}" fill="{fill}"{filt}/>')
    if edge > 0:
        ec = edge_color or color
        stroke = svg.linear([(0, ec, edge), (0.55, ec, edge * 0.35), (1, ec, 0)], x, y, x, y + h)
        dash = ' stroke-dasharray="14 12"' if dashed else ""
        svg.add(f'<path d="{d}" fill="none" stroke="{stroke}" stroke-width="3"{dash}/>')


def _ribbon(svg: Svg, d: str, width: float, opacity: float, colors, soft) -> None:
    a, b, c = colors
    stroke = svg.linear([(0, a, 0), (0.25, a, 1), (0.6, b, 1), (1, c, 0.2)], 0, 0, W, 0)
    svg.add(f'<path d="{d}" fill="none" stroke="{stroke}" stroke-width="{num(width)}" '
            f'stroke-opacity="{num(opacity)}" stroke-linecap="round" filter="{soft}"/>')


def _cloud(svg: Svg, cx: float, cy: float, rx: float, ry: float, color: str, opacity: float) -> None:
    """A soft elliptical cloud (radial gradient, no filter: smooth and cheap)."""
    fill = svg.radial([(0, color, opacity), (0.35, color, opacity * 0.62), (0.7, color, opacity * 0.2),
                       (1, color, 0)], cx, cy, rx, 1.0, ry / rx)
    svg.add(f'<rect width="{W}" height="{H}" fill="{fill}"/>')


# Motifs ----------------------------------------------------------------------
#
# A motif draws in two layers: "back" (behind the orbit) and "front" (in front
# of it, e.g. a horizon that hides the lower rings). Each one also places the
# blade, the third element of the mark's geometry.

def motif_horizon(svg: Svg, v: dict, ctx: dict, layer: str) -> None:
    """A planet horizon lit in the accent colour along its rim."""
    fx, fy = ctx["focus"]
    if layer == "back":
        if not ctx["lock"]:
            _blade(svg, stem_box(fx, fy, ctx["radii"][2]), v["accent_hi"], 0.06, 0.0, edge=0.20, soft=22)
        return
    top_c, bottom_c = v["motif_colors"]
    pcx, pr = 1450.0, 3600.0
    top = 1780.0 if ctx["lock"] else 1700.0
    pcy = top + pr
    # Atmosphere above the rim.
    air = svg.radial([(0, v["accent_hi"], 0.22), (0.45, v["accent"], 0.07), (1, v["accent"], 0)],
                     pcx + 250, top, 2300, 1.0, 0.36)
    svg.add(f'<rect width="{W}" height="{H}" fill="{air}"/>')
    # The planet.
    body = svg.linear([(0, top_c), (1, bottom_c)], 0, top, 0, H)
    svg.add(f'<circle cx="{num(pcx)}" cy="{num(pcy)}" r="{num(pr)}" fill="{body}"/>')
    # Rim light, brightest just right of the peak, fading towards both sides.
    rim = svg.linear([(0, v["accent"], 0), (0.32, v["accent"], 0.55), (0.46, v["accent_hi"], 0.95),
                      (0.68, v["accent"], 0.4), (1, v["accent"], 0)], -200, 0, 3500, 0)
    svg.add(f'<circle cx="{num(pcx)}" cy="{num(pcy)}" r="{num(pr)}" fill="none" stroke="{rim}" '
            f'stroke-width="40" stroke-opacity="0.35" filter="{svg.blur(26)}"/>')
    svg.add(f'<circle cx="{num(pcx)}" cy="{num(pcy)}" r="{num(pr)}" fill="none" stroke="{rim}" stroke-width="4"/>')


def motif_midnight(svg: Svg, v: dict, ctx: dict, layer: str) -> None:
    """Almost nothing: fine meridians and the blade as a hairline."""
    if layer != "back":
        return
    (line,) = v["motif_colors"]
    fx, fy = ctx["focus"]
    parts = []
    for i, r in enumerate((1900, 2150, 2400)):
        parts.append(f'<path d="{arc_path(fx, fy, r, 150, 250)}" stroke-opacity="{num(0.05 - 0.012 * i)}"/>')
    svg.add(f'<g fill="none" stroke="{line}" stroke-width="2">' + "".join(parts) + "</g>")
    if not ctx["lock"]:
        _blade(svg, stem_box(fx, fy, ctx["radii"][3]), line, 0.0, 0.0, edge=0.10)


AURORA_MAIN = "M-300 1050C500 520 1300 1180 2050 820S3300 260 4200 520"


def motif_aurora(svg: Svg, v: dict, ctx: dict, layer: str) -> None:
    """Ribbons of aurora light flowing across the upper half."""
    if layer != "back":
        return
    c1, c2, c3 = v["motif_colors"]
    fx, fy = ctx["focus"]
    soft = svg.blur(70)
    ribbons = [
        (AURORA_MAIN, 300, 0.45, (c1, c2, c3)),
        ("M-300 1350C700 900 1500 1500 2300 1100S3500 700 4200 900", 200, 0.26, (c3, c2, c1)),
        ("M-300 700C600 420 1400 820 2100 560S3400 160 4200 300", 160, 0.20, (c2, c1, c3)),
    ]
    for d, width, opacity, colors in ribbons[:2] if ctx["lock"] else ribbons:
        _ribbon(svg, d, width, opacity, colors, soft)
    # Fine filaments along the main ribbon.
    filament = svg.linear([(0, c1, 0), (0.3, c1, 0.5), (0.7, c2, 0.45), (1, c3, 0)], 0, 0, W, 0)
    for dy in (-34, 0, 30):
        svg.add(f'<path d="M-300 {1050 + dy}C500 {520 + dy} 1300 {1180 + dy} 2050 {820 + dy}'
                f'S3300 {260 + dy} 4200 {520 + dy}" fill="none" stroke="{filament}" stroke-width="2"/>')
    if not ctx["lock"]:
        _blade(svg, stem_box(fx, fy, ctx["radii"][2]), c1, 0.08, 0.0, edge=0.18, soft=26)


def motif_slate(svg: Svg, v: dict, ctx: dict, layer: str) -> None:
    """An architectural glass plane (the blade) and one horizon hairline."""
    if layer != "back":
        return
    (light,) = v["motif_colors"]
    fx, fy = ctx["focus"]
    if not ctx["lock"]:
        _blade(svg, stem_box(fx, fy, ctx["radii"][3]), light, 0.045, 0.0, edge=0.14, soft=30)
    line = svg.linear([(0, light, 0), (0.5, light, 0.10), (1, light, 0)], 0, 0, W, 0)
    svg.add(f'<rect x="0" y="{num(fy + ctx["radii"][1] + 2)}" width="{W}" height="2" fill="{line}"/>')


def motif_carbon(svg: Svg, v: dict, ctx: dict, layer: str) -> None:
    """An engineering grid fading out from the focus, dial ticks and the blade
    drawn as a dashed construction line."""
    if layer != "back":
        return
    (line,) = v["motif_colors"]
    fx, fy = ctx["focus"]
    grid = svg.new_id("grid")
    svg.define(f'<pattern id="{grid}" patternUnits="userSpaceOnUse" width="96" height="96">'
               f'<path d="M96 0H0V96" fill="none" stroke="{line}" stroke-width="1.5"/></pattern>')
    mask = svg.new_id("mask")
    fade = svg.radial([(0, "#FFFFFF", 1), (0.55, "#FFFFFF", 0.35), (1, "#FFFFFF", 0)], fx, fy, 1900)
    svg.define(f'<mask id="{mask}" maskUnits="userSpaceOnUse" x="0" y="0" width="{W}" height="{H}">'
               f'<rect width="{W}" height="{H}" fill="{fade}"/></mask>')
    svg.add(f'<rect width="{W}" height="{H}" fill="url(#{grid})" opacity="{num(0.08 if not ctx["lock"] else 0.05)}" '
            f'mask="url(#{mask})"/>')
    r = ctx["radii"][1]
    ticks = []
    for i in range(72):
        angle = i * 5.0
        length = 34 if i % 6 == 0 else 14
        x0, y0 = polar(fx, fy, r + 10, angle)
        x1, y1 = polar(fx, fy, r + 10 + length, angle)
        ticks.append(f"M{num(x0)} {num(y0)}L{num(x1)} {num(y1)}")
    svg.add(f'<path d="{"".join(ticks)}" stroke="{line}" stroke-opacity="0.22" stroke-width="3" fill="none"/>')
    if not ctx["lock"]:
        _blade(svg, stem_box(fx, fy, ctx["radii"][2]), line, 0.0, 0.0, edge=0.26, dashed=True)


def motif_pearl(svg: Svg, v: dict, ctx: dict, layer: str) -> None:
    """Pearl sheen: soft highlights and a glass blade with a gold edge."""
    if layer != "back":
        return
    sheen, warm = v["motif_colors"]
    fx, fy = ctx["focus"]
    k = 1.0 if ctx["light"] else 0.12   # a sheen on navy must stay a whisper
    _cloud(svg, 900, 300, 1600, 1200, sheen, 0.6 * k)
    _cloud(svg, 3300, 1900, 1400, 900, sheen, 0.35 * k)
    _cloud(svg, 2100, 2300, 2400, 900, warm, 0.6 if ctx["light"] else 0.5)
    if not ctx["lock"]:
        _blade(svg, stem_box(fx, fy, ctx["radii"][2]), sheen, 0.5 * k, 0.0, edge=0.35, soft=24,
               edge_color=v["accent_hi"])


def motif_ocean(svg: Svg, v: dict, ctx: dict, layer: str) -> None:
    """A shaft of light (the blade) above calm, layered swells that catch the
    light along their crests."""
    fx, fy = ctx["focus"]
    if layer == "back":
        if not ctx["lock"]:
            _blade(svg, stem_box(fx, fy, ctx["radii"][2]), v["accent_hi"], 0.07, 0.0, edge=0.16, soft=28)
        return
    shift = 70 if ctx["lock"] else 0
    swells = [
        (1560, 150, v["motif_colors"][0], 0.60),
        (1720, 120, v["motif_colors"][1], 0.80),
        (1880, 90, v["motif_colors"][2], 0.95),
    ]
    glow = svg.blur(18)
    for i, (base, amp, color, opacity) in enumerate(swells):
        base += shift
        phase = (0, 900, 420)[i]
        top_y = base - amp
        crest_d = (f"M0 {num(base + amp * 0.3)}"
                   f"C{num(700 + phase * 0.2)} {num(base - amp)} {num(1500 + phase * 0.3)} {num(base - amp)} "
                   f"{num(2200 + phase * 0.2)} {num(base)}"
                   f"S{num(3300 + phase * 0.1)} {num(base + amp * 0.6)} {W} {num(base - amp * 0.5)}")
        lit = mix(color, v["accent"], 0.22)
        fill = svg.linear([(0, lit, opacity), (0.35, color, opacity), (1, color, opacity * 0.9)],
                          0, top_y, 0, top_y + 600)
        svg.add(f'<path d="{crest_d}V{H}H0Z" fill="{fill}"/>')
        crest = svg.linear([(0, v["accent"], 0), (0.5, v["accent_hi"], 1), (1, v["accent"], 0)],
                           fx - 2600, 0, fx + 1400, 0)
        svg.add(f'<path d="{crest_d}" fill="none" stroke="{crest}" stroke-width="26" '
                f'stroke-opacity="{num(0.16 - 0.03 * i)}" filter="{glow}"/>')
        svg.add(f'<path d="{crest_d}" fill="none" stroke="{crest}" stroke-width="3" '
                f'stroke-opacity="{num(0.42 - 0.08 * i)}"/>')
    # The light of the focus, reflected on the water.
    _cloud(svg, fx, 1900 + shift, 700, 170, v["accent_hi"], 0.14)


EMBER_FLOW = "M-200 2150C900 2050 1500 1650 2300 1450S3500 950 4200 650"


def motif_ember(svg: Svg, v: dict, ctx: dict, layer: str) -> None:
    """A warm current rising from the lower right (the mark's swoosh), embers
    and a light shaft."""
    if layer != "back":
        return
    copper, flame, deep = v["motif_colors"]
    fx, fy = ctx["focus"]
    _cloud(svg, 3300, 2250, 2300, 1500, flame, 0.30)
    _cloud(svg, 3600, 1900, 1200, 900, deep, 0.25)
    soft = svg.blur(60)
    _ribbon(svg, EMBER_FLOW, 260, 0.38 if not ctx["light"] else 0.24, (deep, copper, flame), soft)
    if not ctx["lock"]:
        _ribbon(svg, "M-200 1900C800 1880 1500 1500 2400 1250S3500 700 4200 380", 120, 0.22,
                (deep, flame, copper), soft)
    filament = svg.linear([(0, copper, 0), (0.4, copper, 0.45), (0.8, flame, 0.5), (1, flame, 0)], 0, 0, W, 0)
    for dy in (-26, 4, 30):
        svg.add(f'<path d="M-200 {2150 + dy}C900 {2050 + dy} 1500 {1650 + dy} 2300 {1450 + dy}'
                f'S3500 {950 + dy} 4200 {650 + dy}" fill="none" stroke="{filament}" stroke-width="2"/>')
    if not ctx["lock"]:
        _blade(svg, stem_box(fx, fy, ctx["radii"][2]), flame, 0.07, 0.0, edge=0.18, soft=26)
    rng = Rng(ctx["id"])
    dots = []
    for _ in range(14 if ctx["lock"] else 30):
        x = rng.uniform(1800, 3800)
        y = rng.uniform(700, 2050)
        r = rng.uniform(2.5, 7.0)
        op = rng.uniform(0.2, 0.7) * min(1.0, max(0.15, (x - 1600) / 2200))
        dots.append(f'<circle cx="{num(x)}" cy="{num(y)}" r="{num(r)}" fill-opacity="{num(op)}"/>')
    svg.add(f'<g fill="{v["accent_hi"]}">' + "".join(dots) + "</g>")


def motif_nebula(svg: Svg, v: dict, ctx: dict, layer: str) -> None:
    """Nebula clouds, a sparse star field and a faint blade."""
    if layer != "back":
        return
    violet, blue, magenta, deep = v["motif_colors"]
    fx, fy = ctx["focus"]
    _cloud(svg, 2700, 900, 1250, 800, violet, 0.42)
    _cloud(svg, 2050, 1350, 1300, 600, blue, 0.30)
    _cloud(svg, 3400, 1380, 900, 650, magenta, 0.24)
    _cloud(svg, 3050, 520, 700, 420, magenta, 0.12)
    _cloud(svg, 500, 1900, 1700, 900, deep, 0.45)
    rng = Rng(ctx["id"])
    stars = []
    for _ in range(60 if ctx["lock"] else 110):
        x, y = rng.uniform(0, W), rng.uniform(0, H * 0.92)
        r = rng.uniform(1.2, 3.4)
        op = rng.uniform(0.15, 0.75)
        stars.append(f'<circle cx="{num(x)}" cy="{num(y)}" r="{num(r)}" fill-opacity="{num(op)}"/>')
    svg.add(f'<g fill="{v["accent_hi"]}">' + "".join(stars) + "</g>")
    if not ctx["lock"]:
        _blade(svg, stem_box(fx, fy, ctx["radii"][2]), v["accent_hi"], 0.06, 0.0, edge=0.16, soft=26)


def motif_classic(svg: Svg, v: dict, ctx: dict, layer: str) -> None:
    """Plain: a hairline blade only (cheap to render, small to store)."""
    if layer == "back" and not ctx["lock"]:
        fx, fy = ctx["focus"]
        _blade(svg, stem_box(fx, fy, ctx["radii"][2]), v["ring"], 0.0, 0.0, edge=v["ring_opacity"] * 1.4)


MOTIFS = {
    "horizon": motif_horizon,
    "midnight": motif_midnight,
    "aurora": motif_aurora,
    "slate": motif_slate,
    "carbon": motif_carbon,
    "pearl": motif_pearl,
    "ocean": motif_ocean,
    "ember": motif_ember,
    "nebula": motif_nebula,
    "classic": motif_classic,
}


def wallpaper_svg(p: dict, variant: str, lock: bool = False) -> str:
    wp = p["wallpaper"]
    v = wp[variant]
    motif = MOTIFS[wp["motif"]]
    plain = wp["motif"] == "classic"
    fx, fy = wp["focus"]
    mark_h = wp["mark_height"]
    if lock:
        # Keep the centre and left calm for the clock and the password field.
        fx, fy = max(fx, 3000.0), fy + 120
        mark_h *= 0.8
    kind = "lock screen" if lock else f"{variant} wallpaper"
    svg = Svg("w", W, H, f"{p['name']} {kind}")
    r0 = mark_h * MARK_RING / MARK_H
    light = not is_dark(v["base"][1])
    ctx = {"focus": (fx, fy), "lock": lock, "id": p["id"], "light": light,
           "radii": [r0 * 1.55 * 1.42 ** i for i in range(5)]}
    radii = ctx["radii"]

    _base(svg, v, vertical=plain)
    _glows(svg, v, fx, fy)
    motif(svg, v, ctx, "back")
    _orbit(svg, v, fx, fy, r0, count=3 if (lock or plain) else 5)
    motif(svg, v, ctx, "front")
    if lock:
        _trail(svg, v, fx, fy, radii[1], 215, 285, width=5, dot=12, strength=0.75, light=light)
    else:
        _trail(svg, v, fx, fy, radii[1], 200, 292, strength=0.7 if plain else 1.0, light=light)
        if not plain:
            _trail(svg, v, fx, fy, radii[3], 18, 46, width=3, dot=0, strength=0.5)
    _mark(svg, fx, fy, mark_h, v["mark"], v["mark_opacity"])
    return svg.render()


def wallpaper_metadata(wallpaper_id: str, name: str) -> str:
    return dump_json({
        "KPlugin": {
            "Authors": [{"Name": AUTHOR}],
            "Id": wallpaper_id,
            "License": LICENSE,
            "Name": name,
        },
    })


# --------------------------------------------------------------------------
# Previews: the wallpaper with a schematic window and panel
# --------------------------------------------------------------------------

PW, PH = 1920, 1080


def preview_svg(p: dict) -> str:
    c = p["palette"]
    svg = Svg("p", PW, PH, f"{p['name']} preview")
    svg.add(f'<image x="0" y="0" width="{PW}" height="{PH}" '
            f'href="../wallpapers/{wallpaper_name(p)}/{primary(p)}.svg"/>')

    def rect(x, y, w, h, fill, rx=0.0, opacity=1.0, extra=""):
        op = "" if opacity >= 1.0 else f' fill-opacity="{num(opacity)}"'
        rr = f' rx="{num(rx)}"' if rx else ""
        svg.add(f'<rect x="{num(x)}" y="{num(y)}" width="{num(w)}" height="{num(h)}"{rr} fill="{fill}"{op}{extra}/>')

    def text_line(x, y, w, color, opacity=0.85, h=11.0):
        rect(x, y - h / 2, w, h, color, h / 2, opacity)

    # Window ------------------------------------------------------------
    wx, wy, ww, wh = 150.0, 120.0, 1140.0, 700.0
    shadow = svg.blur(26)
    svg.add(f'<rect x="{num(wx)}" y="{num(wy + 22)}" width="{num(ww)}" height="{num(wh)}" rx="14" '
            f'fill="#000000" fill-opacity="0.45" filter="{shadow}"/>')
    clip = svg.new_id("clip")
    svg.define(f'<clipPath id="{clip}"><rect x="{num(wx)}" y="{num(wy)}" width="{num(ww)}" '
               f'height="{num(wh)}" rx="12"/></clipPath>')
    svg.add(f'<g clip-path="url(#{clip})">')
    # Title bar and tool bar share the Header colours.
    rect(wx, wy, ww, 106, c["header"])
    text_line(wx + ww / 2 - 120, wy + 26, 240, c["text"], 0.8)
    for i, color in enumerate((c["muted"], c["muted"], c["muted"])):
        svg.add(f'<circle cx="{num(wx + ww - 32 - 38 * i)}" cy="{num(wy + 26)}" r="9" fill="{color}" fill-opacity="0.8"/>')
    for i in range(4):
        rect(wx + 20 + 44 * i, wy + 62, 28, 28, c["muted"], 7, 0.55)
    rect(wx + ww - 330, wy + 59, 310, 34, c["view"], 9, 1.0,
         f' stroke="{c["muted"]}" stroke-opacity="0.35" stroke-width="1.5"')
    text_line(wx + ww - 312, wy + 76, 120, c["muted"], 0.7, 9)
    # Sidebar (Window colours).
    sx, sy, sw = wx, wy + 106, 270.0
    rect(sx, sy, sw, wh - 106, c["window"])
    text_line(sx + 24, sy + 34, 90, c["muted"], 0.8, 9)
    for i in range(7):
        iy = sy + 66 + i * 50
        if i == 1:
            rect(sx + 10, iy - 20, sw - 20, 40, c["selection"], 8)
            fg = c["selection_text"]
        else:
            fg = c["text"]
        rect(sx + 24, iy - 10, 20, 20, c["accent"] if i == 1 else c["muted"], 5,
             1.0 if i == 1 else 0.6)
        if i == 1:
            rect(sx + 24, iy - 10, 20, 20, c["selection_text"], 5, 0.85)
        text_line(sx + 56, iy, [140, 112, 128, 96, 150, 120, 104][i], fg, 0.9)
    # Content (View colours).
    vx, vy = sx + sw, sy
    vw, vh = ww - sw, wh - 106 - 56
    rect(vx, vy, vw, vh, c["view"])
    rect(vx, vy, vw, 40, c["window_alt"])
    for col, w in ((24, 120), (480, 70), (660, 90)):
        text_line(vx + col, vy + 20, w, c["muted"], 0.8, 9)
    for i in range(9):
        ry = vy + 40 + i * 46
        if i == 2:
            rect(vx, ry, vw, 46, c["selection"])
            fg, meta = c["selection_text"], c["selection_text"]
        else:
            if i % 2:
                rect(vx, ry, vw, 46, c["view_alt"])
            fg, meta = c["text"], c["muted"]
        rect(vx + 24, ry + 12, 22, 22, c["accent"] if i in (0, 4) else c["muted"], 5,
             0.9 if i in (0, 4) else 0.55)
        text_line(vx + 60, ry + 23, [210, 180, 240, 160, 200, 230, 170, 190, 150][i], fg, 0.9)
        text_line(vx + 480, ry + 23, 80, meta, 0.7, 9)
        text_line(vx + 660, ry + 23, 110, meta, 0.7, 9)
    # Status bar with a progress bar and the dialog buttons.
    by = wy + wh - 56
    rect(vx, by, vw, 56, c["window"])
    rect(vx + 24, by + 24, 220, 8, c["window_alt"], 4)
    rect(vx + 24, by + 24, 140, 8, c["selection"], 4)
    rect(vx + vw - 300, by + 10, 130, 36, c["button"], 8, 1.0,
         f' stroke="{c["muted"]}" stroke-opacity="0.4" stroke-width="1.5"')
    text_line(vx + vw - 270, by + 28, 70, c["text"], 0.85, 9)
    rect(vx + vw - 156, by + 10, 130, 36, c["button"], 8, 1.0,
         f' stroke="{c["accent"]}" stroke-width="3"')
    text_line(vx + vw - 126, by + 28, 70, c["text"], 0.9, 9)
    svg.add("</g>")

    # Panel -------------------------------------------------------------
    full = p["panel"]["style"] == "full-width"
    if full:
        px, py, pw, ph, prx = 0.0, PH - 44.0, float(PW), 44.0, 0.0
    else:
        px, py, pw, ph, prx = 10.0, PH - 56.0, PW - 20.0, 46.0, 10.0
    rect(px, py, pw, ph, c["window"], prx, 0.96,
         f' stroke="{c["text"]}" stroke-opacity="0.10" stroke-width="1.5"')
    cy = py + ph / 2
    # Launcher: the mark.
    _mark(svg, px + 30, cy, 30, "colour", 1.0, branding="../../branding")
    # Pager.
    for i in range(2):
        rect(px + 58 + 30 * i, cy - 10, 24, 20, c["muted"], 3, 0.25 if i else 0.5)
    x = px + 130
    if full:
        for i in range(4):
            active = i == 1
            if active:
                rect(x - 4, py + 4, 196, ph - 8, c["selection"], 4, 0.30)
            rect(x + 4, cy - 12, 24, 24, c["accent"] if i == 0 else c["muted"], 6, 0.85)
            text_line(x + 38, cy, [110, 130, 96, 120][i], c["text"], 0.85, 9)
            if active:
                rect(x - 4, py + ph - 4, 196, 3, c["accent"])
            x += 204
    else:
        for i in range(5):
            rect(x, cy - 15, 30, 30, c["accent"] if i == 0 else c["muted"], 8,
                 0.9 if i == 0 else 0.6)
            if i in (1, 2):
                rect(x + 6, py + ph - 5, 18, 3, c["accent"], 1.5)
            x += 46
    # System tray and clock.
    tx = px + pw - 250
    for i in range(4):
        svg.add(f'<circle cx="{num(tx + 30 * i)}" cy="{num(cy)}" r="8" fill="{c["muted"]}" fill-opacity="0.75"/>')
    text_line(px + pw - 120, cy - 7, 70, c["text"], 0.9, 9)
    text_line(px + pw - 128, cy + 9, 86, c["muted"], 0.8, 7)
    return svg.render()


# --------------------------------------------------------------------------
# Output tree
# --------------------------------------------------------------------------

def load(path: Path) -> dict:
    with path.open(encoding="utf-8") as handle:
        return json.load(handle)


def outputs(data: dict) -> dict[str, str]:
    files: dict[str, str] = {}
    for p in data["presets"]:
        files[f"color-schemes/{scheme_name(p)}.colors"] = colors_file(p)
        files[f"konsole/{scheme_name(p)}.colorscheme"] = konsole_scheme(p)
        files[f"konsole/{profile_name(p)}"] = konsole_profile(p)
        lnf = f"look-and-feel/{lnf_id(p)}"
        files[f"{lnf}/metadata.json"] = lnf_metadata(p)
        files[f"{lnf}/contents/defaults"] = lnf_defaults(p)
        files[f"{lnf}/contents/layouts/org.kde.plasma.desktop-layout.js"] = layout_js(p)
        wall = f"wallpapers/{wallpaper_name(p)}"
        files[f"{wall}/metadata.json"] = wallpaper_metadata(wallpaper_name(p), p["name"])
        files[f"{wall}/light.svg"] = wallpaper_svg(p, "light")
        files[f"{wall}/dark.svg"] = wallpaper_svg(p, "dark")
        files[f"{wall}/lock.svg"] = wallpaper_svg(p, primary(p), lock=True)
        files[f"previews/{p['id']}.svg"] = preview_svg(p)
    # The system default wallpaper name ("Boswas"): a copy of the default preset's.
    files["wallpapers/Boswas/metadata.json"] = wallpaper_metadata("Boswas", "Boswas")
    return files


def write_tree(root: Path, files: dict[str, str], prune: bool) -> list[str]:
    changed = []
    for rel, text in sorted(files.items()):
        path = root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        old = path.read_bytes() if path.exists() else None
        new = text.encode("utf-8")
        if old != new:
            with path.open("w", encoding="utf-8", newline="") as handle:
                handle.write(text)
            changed.append(rel)
    if prune:
        for top in GENERATED_DIRS:
            base = root / top
            if not base.exists():
                continue
            for path in sorted(base.rglob("*"), reverse=True):
                rel = path.relative_to(root).as_posix()
                if path.is_file() and rel not in files:
                    path.unlink()
                    changed.append(f"{rel} (removed)")
                elif path.is_dir() and not any(path.iterdir()):
                    path.rmdir()
    return changed


def stale(root: Path, files: dict[str, str]) -> list[str]:
    problems = []
    for rel, text in sorted(files.items()):
        path = root / rel
        if not path.exists():
            problems.append(f"missing: {rel}")
        elif path.read_bytes() != text.encode("utf-8"):
            problems.append(f"out of date: {rel}")
    for top in GENERATED_DIRS:
        base = root / top
        if base.exists():
            for path in sorted(base.rglob("*")):
                rel = path.relative_to(root).as_posix()
                if path.is_file() and rel not in files:
                    problems.append(f"not generated: {rel}")
    return problems


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--presets", type=Path, default=PRESETS_DIR / "presets.json",
                        help="presets file (default: %(default)s)")
    parser.add_argument("--output", type=Path, help="write the generated tree here")
    parser.add_argument("--check", action="store_true", help="only check that files are up to date")
    args = parser.parse_args(argv)

    files = outputs(load(args.presets))
    if args.check:
        problems = stale(args.output or PRESETS_DIR, files)
        for problem in problems:
            print(problem, file=sys.stderr)
        if problems:
            print("Run desktop/presets/tools/build_presets.py to regenerate.", file=sys.stderr)
        return 1 if problems else 0
    root = args.output or PRESETS_DIR
    changed = write_tree(root, files, prune=True)
    for rel in changed:
        print(rel)
    print(f"{len(files)} files, {len(changed)} changed", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
