#!/usr/bin/env python3
"""Generate the Boswas icon theme.

Every icon is drawn here, on a 256x256 grid, and written as a self-contained
SVG into desktop/icons/Boswas/scalable/{apps,mimetypes}/. The generated files
are committed; re-run this tool after changing a glyph:

    python3 desktop/icons/tools/build_icons.py            # regenerate in place
    python3 desktop/icons/tools/build_icons.py --output DIR
    python3 desktop/icons/tools/build_icons.py --table    # README name table

The official Boswas OS mark is not redrawn: its path data and gradients are
copied from desktop/branding/boswas-os-mark.svg at build time.

Design rules (see desktop/icons/README.md):
  * apps sit on the navy launcher tile of desktop/branding/boswas-mark.svg
    (x=8 y=8 240x240 rx=56, gradient #162034 -> #080C16, thin gold edge);
  * glyphs are line art, stroke 14, round caps and joins, in the silver
    gradient, inside roughly 56..200, with ONE gold accent element;
  * mimetypes are flat light pages with a navy glyph and a gold accent;
  * every id is prefixed with the file's own name, so files can be combined;
  * only features Qt's SVG renderer supports: paths, linear gradients in user
    space, solid fills and strokes. No masks, clip paths, filters, CSS,
    <text>, <image> or nested <svg>.

Python 3 standard library only. Output is deterministic.
"""

from __future__ import annotations

import argparse
import math
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

HERE = Path(__file__).resolve().parent
ICONS_DIR = HERE.parent
REPO = ICONS_DIR.parent.parent
BRANDING = REPO / "desktop" / "branding"
DEFAULT_OUTPUT = ICONS_DIR / "Boswas"
HEADER = "Generated by desktop/icons/tools/build_icons.py; do not edit by hand."
SVG_NS = "http://www.w3.org/2000/svg"

# ---------------------------------------------------------------------------
# Palette (desktop/branding/README.md)
# ---------------------------------------------------------------------------
NAVY_900 = "#0B1220"
NAVY_800 = "#111A2B"

# name -> (attributes, stops). Stops are (offset, colour, opacity). All are
# linear gradients in user space: a horizontal or vertical stroke has a
# bounding box without area, and would not be painted by a gradient in
# objectBoundingBox units. One shared vector also lights every glyph alike
# (light at the top left, darker at the bottom right).
GRADIENTS = {
    "tile": ({"x1": "8", "y1": "8", "x2": "248", "y2": "248"},
             [(0, "#162034", 1), (1, "#080C16", 1)]),
    "edge": ({"x1": "8", "y1": "8", "x2": "248", "y2": "248"},
             [(0, "#FBD693", 0.85), (1, "#B5935C", 0.45)]),
    "silver": ({"x1": "72", "y1": "48", "x2": "184", "y2": "208"},
               [(0, "#D4DDEC", 1), (1, "#6E7A8F", 1)]),
    "gold": ({"x1": "72", "y1": "48", "x2": "184", "y2": "208"},
             [(0, "#FBD693", 1), (1, "#B5935C", 1)]),
    "page": ({"x1": "56", "y1": "24", "x2": "200", "y2": "232"},
             [(0, "#E8EEF6", 1), (1, "#AEB7C7", 1)]),
    "fold": ({"x1": "156", "y1": "24", "x2": "200", "y2": "68"},
             [(0, "#AEB7C7", 1), (1, "#6E7A8F", 1)]),
}
# The mark's own gradients, copied from the traced mark (see load_mark).
MARK_GRADIENTS = {"markgold": "boswas-mark-gold", "marksilver": "boswas-mark-silver"}

W = 14  # standard stroke width on the 256 grid


# ---------------------------------------------------------------------------
# Number and path helpers
# ---------------------------------------------------------------------------
def n(v: float) -> str:
    """Format a coordinate compactly and deterministically."""
    v = round(v, 2)
    if v == int(v):
        return str(int(v))
    return f"{v:.2f}".rstrip("0").rstrip(".")


def pt(x: float, y: float) -> str:
    return f"{n(x)} {n(y)}"


def polar(cx: float, cy: float, r: float, deg: float) -> tuple[float, float]:
    """Point at clock angle deg (0 = 12 o'clock, clockwise)."""
    a = math.radians(deg)
    return cx + r * math.sin(a), cy - r * math.cos(a)


def line(*pts: tuple[float, float]) -> str:
    return "M" + "L".join(pt(x, y) for x, y in pts)


def poly(*pts: tuple[float, float]) -> str:
    return line(*pts) + "Z"


def rr(x: float, y: float, w: float, h: float, r: float) -> str:
    """Rounded rectangle as path data."""
    return (f"M{pt(x + r, y)}H{n(x + w - r)}A{n(r)} {n(r)} 0 0 1 {pt(x + w, y + r)}"
            f"V{n(y + h - r)}A{n(r)} {n(r)} 0 0 1 {pt(x + w - r, y + h)}"
            f"H{n(x + r)}A{n(r)} {n(r)} 0 0 1 {pt(x, y + h - r)}"
            f"V{n(y + r)}A{n(r)} {n(r)} 0 0 1 {pt(x + r, y)}Z")


def circle(cx: float, cy: float, r: float) -> str:
    return (f"M{pt(cx - r, cy)}A{n(r)} {n(r)} 0 1 0 {pt(cx + r, cy)}"
            f"A{n(r)} {n(r)} 0 1 0 {pt(cx - r, cy)}Z")


def ellipse(cx: float, cy: float, rx: float, ry: float) -> str:
    return (f"M{pt(cx, cy - ry)}A{n(rx)} {n(ry)} 0 1 1 {pt(cx, cy + ry)}"
            f"A{n(rx)} {n(ry)} 0 1 1 {pt(cx, cy - ry)}Z")


def arc(cx: float, cy: float, r: float, a0: float, a1: float) -> str:
    """Clockwise arc from clock angle a0 to a1 (degrees)."""
    sweep = (a1 - a0) % 360 or 360
    x0, y0 = polar(cx, cy, r, a0)
    x1, y1 = polar(cx, cy, r, a1)
    large = 1 if sweep > 180 else 0
    return f"M{pt(x0, y0)}A{n(r)} {n(r)} 0 {large} 1 {pt(x1, y1)}"


def arc_tangent(deg: float) -> tuple[float, float]:
    """Direction of travel of a clockwise arc at clock angle deg."""
    a = math.radians(deg)
    return math.cos(a), math.sin(a)


def arrowhead(tip: tuple[float, float], direction: tuple[float, float],
              size: float = 22, spread: float = 42) -> str:
    """Open chevron at tip, pointing along direction."""
    dx, dy = direction
    length = math.hypot(dx, dy)
    dx, dy = dx / length, dy / length
    ends = []
    for s in (spread, -spread):
        a = math.radians(s)
        bx = -dx * math.cos(a) + dy * math.sin(a)
        by = -dx * math.sin(a) - dy * math.cos(a)
        ends.append((tip[0] + bx * size, tip[1] + by * size))
    return line(ends[0], tip, ends[1])


def gear(cx: float, cy: float, teeth: int, r_out: float, r_in: float,
         top: float, base: float, phase: float = 0) -> str:
    """Gear outline: trapezoid teeth joined by root arcs (angles in degrees)."""
    pitch = 360 / teeth
    d = []
    for i in range(teeth):
        a = phase + i * pitch
        p1 = polar(cx, cy, r_in, a - base)
        p2 = polar(cx, cy, r_out, a - top)
        p3 = polar(cx, cy, r_out, a + top)
        p4 = polar(cx, cy, r_in, a + base)
        nxt = polar(cx, cy, r_in, a + pitch - base)
        if i == 0:
            d.append("M" + pt(*p1))
        d.append(f"L{pt(*p2)}L{pt(*p3)}L{pt(*p4)}A{n(r_in)} {n(r_in)} 0 0 1 {pt(*nxt)}")
    return "".join(d) + "Z"


def shield(cx: float, top: float, half: float, height: float) -> str:
    """Heater shield: flat shoulders, curved sides meeting in a point."""
    y1 = top + height * 0.16
    mid = top + height * 0.52
    bottom = top + height
    return (f"M{pt(cx, top)}L{pt(cx + half, y1)}V{n(mid)}"
            f"Q{pt(cx + half, bottom - height * 0.14)} {pt(cx, bottom)}"
            f"Q{pt(cx - half, bottom - height * 0.14)} {pt(cx - half, mid)}"
            f"V{n(y1)}Z")


def pencil(tail: tuple[float, float], tip: tuple[float, float], width: float = 24,
           point: float = 26) -> str:
    """Pencil silhouette (body plus sharpened point) from tail to tip."""
    tx, ty = tail
    px, py = tip
    length = math.hypot(px - tx, py - ty)
    ux, uy = (px - tx) / length, (py - ty) / length
    nx, ny = -uy * width / 2, ux * width / 2
    bx, by = px - ux * point, py - uy * point
    return poly((tx + nx, ty + ny), (bx + nx, by + ny), (px, py),
                (bx - nx, by - ny), (tx - nx, ty - ny))


# ---------------------------------------------------------------------------
# Element helpers. A paint is a "$name" token for a gradient (resolved per
# file into url(#<file>-<name>)) or a plain hex colour.
# ---------------------------------------------------------------------------
SILVER = "$silver"
GOLD = "$gold"
TILE = "$tile"
PAGE_PAINT = "$page"
INK = NAVY_800  # glyph colour on the light mimetype page


def stroke(d: str, paint: str = SILVER, w: float = W) -> str:
    return (f'<path d="{d}" fill="none" stroke="{paint}" stroke-width="{n(w)}" '
            f'stroke-linecap="round" stroke-linejoin="round"/>')


def fill(d: str, paint: str = SILVER) -> str:
    return f'<path d="{d}" fill="{paint}"/>'


def solid(d: str, paint: str = GOLD, w: float = 6) -> str:
    """Filled shape with a thin stroke of the same paint (softened corners)."""
    return (f'<path d="{d}" fill="{paint}" stroke="{paint}" stroke-width="{n(w)}" '
            f'stroke-linecap="round" stroke-linejoin="round"/>')


def knock(d: str, w: float = 2 * W, paint: str = TILE) -> str:
    """Halo in the background paint, so an accent stands clear of lines below.

    The background gradients are opaque and in user space, so the halo is
    invisible against the tile (or page) and only interrupts the lines."""
    return solid(d, paint, w)


# ---------------------------------------------------------------------------
# The traced Boswas OS mark, copied from desktop/branding
# ---------------------------------------------------------------------------
_MARK: dict = {}


def load_mark() -> dict:
    if _MARK:
        return _MARK
    root = ET.parse(BRANDING / "boswas-os-mark.svg").getroot()
    gradients = {}
    for grad in root.iter(f"{{{SVG_NS}}}linearGradient"):
        attrs = {k: grad.get(k) for k in ("gradientUnits", "x1", "y1", "x2", "y2") if grad.get(k)}
        stops = [(s.get("offset"), s.get("stop-color"), 1) for s in grad.iter(f"{{{SVG_NS}}}stop")]
        gradients[grad.get("id")] = (attrs, stops)
    groups = []
    for g in root.findall(f"{{{SVG_NS}}}g"):
        groups.append((g.get("transform"),
                       [(p.get("fill"), p.get("d")) for p in g.findall(f"{{{SVG_NS}}}path")]))
    _MARK.update(viewbox=[float(v) for v in root.get("viewBox").split()],
                 gradients=gradients, groups=groups)
    return _MARK


def mark(x: float, y: float, w: float, h: float) -> str:
    """The full-colour mark fitted (centred, aspect kept) into a box."""
    data = load_mark()
    vx, vy, vw, vh = data["viewbox"]
    s = min(w / vw, h / vh)
    dx = x + (w - vw * s) / 2 - vx * s
    dy = y + (h - vh * s) / 2 - vy * s
    tokens = {f"url(#{source})": f"${name}" for name, source in MARK_GRADIENTS.items()}
    out = [f'<g transform="translate({dx:.3f} {dy:.3f}) scale({s:.6f})">']
    for transform, paths in data["groups"]:
        out.append(f'<g transform="{transform}">')
        for paint, d in paths:
            out.append(f'<path fill="{tokens.get(paint, paint)}" d="{d}"/>')
        out.append("</g>")
    out.append("</g>")
    return "\n".join(out)


# ---------------------------------------------------------------------------
# Shared glyph parts
# ---------------------------------------------------------------------------
def window(x: float = 52, y: float = 60, w: float = 136, h: float = 112) -> list[str]:
    """Generic application window: frame plus title bar (not any vendor's logo)."""
    return [stroke(rr(x, y, w, h, 18)), stroke(line((x, y + 30), (x + w, y + 30)))]


BADGE = (170, 170)  # centre of the accent badge on window glyphs


def badge_disc(symbol: list[str], r: float = 38) -> list[str]:
    """Gold disc badge with a navy symbol, cut clear of the glyph below."""
    cx, cy = BADGE
    return [knock(circle(cx, cy, r), 22), fill(circle(cx, cy, r), GOLD)] + symbol


# ---------------------------------------------------------------------------
# Glyphs: one function per design; the docstring is the README description.
# Each returns the SVG elements drawn over the tile (apps) or page (mimetypes).
# ---------------------------------------------------------------------------
def g_settings():
    """Eight-tooth gear, gold hub."""
    return [stroke(gear(128, 128, 8, 70, 50, 10.5, 16)), fill(circle(128, 128, 21), GOLD)]


def g_info():
    """Processor chip with pins, gold "i" (dot and blade stem)."""
    pins = []
    for c in (102, 128, 154):
        pins += [line((c, 56), (c, 80)), line((c, 176), (c, 200)),
                 line((56, c), (80, c)), line((176, c), (200, c))]
    i_mark = circle(128, 104, 10) + "M120 124L136 118V150A8 8 0 0 1 120 150Z"
    return [stroke(rr(80, 80, 96, 96, 16))] + [stroke(p, w=12) for p in pins] + [fill(i_mark, GOLD)]


def g_terminal():
    """Console window with a prompt chevron, gold cursor."""
    return [stroke(rr(56, 64, 144, 128, 20)),
            stroke(line((86, 104), (110, 128), (86, 152))),
            stroke(line((124, 154), (166, 154)), GOLD)]


def g_files():
    """Folder, gold pocket edge."""
    folder = ("M56 92V82Q56 68 70 68H100Q108 68 113 73L124 84H186Q200 84 200 98"
              "V174Q200 188 186 188H70Q56 188 56 174Z")
    return [stroke(folder), stroke(line((56, 114), (200, 114)), GOLD)]


def g_monitor():
    """Screen with a gold activity trace."""
    trace = line((74, 134), (98, 134), (112, 100), (134, 162), (150, 116), (162, 134), (182, 134))
    return [stroke(rr(56, 64, 144, 128, 20)), stroke(trace, GOLD)]


def g_htop():
    """Console window with load bars, the tallest gold."""
    return [stroke(rr(56, 64, 144, 128, 20)),
            stroke(line((94, 164), (94, 124))),
            stroke(line((128, 164), (128, 94)), GOLD),
            stroke(line((162, 164), (162, 138)))]


def g_browser():
    """Globe with equator, gold meridian (a generic browser, not a vendor logo)."""
    return [stroke(circle(128, 128, 68)), stroke(line((62, 128), (194, 128))),
            stroke(ellipse(128, 128, 30, 68), GOLD)]


def g_calculator():
    """Calculator with plus, minus, times and equals keys, gold display."""
    keys = [line((92, 142), (116, 142)), line((104, 130), (104, 154)),
            line((140, 142), (164, 142)),
            line((95, 171), (113, 189)), line((113, 171), (95, 189)),
            line((140, 174), (164, 174)), line((140, 188), (164, 188))]
    return ([stroke(rr(68, 52, 120, 152, 22)), solid(rr(90, 74, 76, 30, 6), GOLD, 4)] +
            [stroke(d, w=11) for d in keys])


def g_editor():
    """Page with text lines, gold pencil."""
    page = "M78 52H138L172 86V190Q172 204 158 204H78Q64 204 64 190V66Q64 52 78 52Z"
    tip = pencil((206, 96), (142, 178))
    return [stroke(page), stroke("M138 52V74Q138 86 150 86H172"),
            stroke(line((90, 118), (142, 118))), stroke(line((90, 146), (126, 146))),
            stroke(line((90, 174), (112, 174))),
            knock(tip, 28), solid(tip, GOLD, 4)]


def g_image():
    """Picture frame with mountains, gold sun."""
    return [stroke(rr(56, 64, 144, 128, 20)),
            stroke(line((76, 170), (110, 128), (134, 154), (150, 138), (180, 170))),
            fill(circle(156, 102, 13), GOLD)]


def g_book():
    """Open book, gold bookmark ribbon."""
    pages = "M128 90Q102 72 62 76V176Q102 172 128 190Q154 172 194 176V76Q154 72 128 90Z"
    return [stroke(pages), stroke(line((128, 90), (128, 186))),
            solid("M152 66V120L163 110L174 120V66Z", GOLD, 4)]


def g_archive():
    """Archive box with lid, gold handle slot."""
    body = "M70 102V178Q70 192 84 192H172Q186 192 186 178V102"
    return [stroke(rr(56, 64, 144, 38, 12)), stroke(body),
            stroke(line((108, 134), (148, 134)), GOLD)]


def g_screenshot():
    """Viewfinder corners, gold shutter dot."""
    corners = ["M60 104V78Q60 60 78 60H104", "M152 60H178Q196 60 196 78V104",
               "M196 152V178Q196 196 178 196H152", "M104 196H78Q60 196 60 178V152"]
    return [stroke(c) for c in corners] + [fill(circle(128, 128, 24), GOLD)]


def g_help():
    """Ring, gold question mark."""
    hook = "M104 108Q104 82 128 82Q152 82 152 105Q152 119 139 126Q128 132 128 146"
    return [stroke(circle(128, 128, 68)),
            stroke(hook, GOLD, 16), fill(circle(128, 172, 10), GOLD)]


def g_find():
    """Magnifying glass, gold handle."""
    return [stroke(circle(112, 112, 46)), stroke(line((148, 148), (190, 190)), GOLD, 24)]


def g_wallet():
    """Wallet with a pocket flap, gold clasp."""
    pocket = "M200 106H160Q144 106 144 122V138Q144 154 160 154H200"
    return [stroke(rr(56, 72, 144, 116, 20)), stroke(pocket), fill(circle(166, 130, 10), GOLD)]


def g_partition():
    """Disk as a pie, one gold partition pulled out."""
    c, r = (128, 132), 64
    p0, p1 = polar(*c, r, 120), polar(*c, r, 360)
    rest = f"M{pt(*c)}L{pt(*p0)}A{r} {r} 0 1 1 {pt(*p1)}Z"
    oc = polar(*c, 12, 60)
    q0, q1 = polar(*oc, r, 0), polar(*oc, r, 120)
    wedge = f"M{pt(*oc)}L{pt(*q0)}A{r} {r} 0 0 1 {pt(*q1)}Z"
    return [stroke(rest), solid(wedge, GOLD, 8)]


def g_menuedit():
    """Menu lines, gold pencil."""
    tip = pencil((206, 132), (148, 196), 24, 24)
    return [stroke(line((60, 80), (196, 80))), stroke(line((60, 124), (196, 124))),
            stroke(line((60, 168), (130, 168))), knock(tip, 28), solid(tip, GOLD, 4)]


def g_bug():
    """Beetle with legs and antennae, gold head."""
    legs = [line((92, 128), (64, 116)), line((90, 152), (60, 152)), line((96, 176), (68, 192)),
            line((164, 128), (192, 116)), line((166, 152), (196, 152)), line((160, 176), (188, 192)),
            line((114, 84), (102, 64)), line((142, 84), (154, 64))]
    return ([stroke(d, w=12) for d in legs] +
            [stroke(ellipse(128, 150, 38, 48)), stroke(line((128, 112), (128, 190)), w=12),
             solid("M104 100A24 24 0 0 1 152 100Z", GOLD, 6)])


def g_emoji():
    """Smiling face, gold smile."""
    return [stroke(circle(128, 128, 68)), fill(circle(104, 112, 11)), fill(circle(152, 112, 11)),
            stroke("M94 146Q128 182 162 146", GOLD)]


def g_network():
    """Wireless arcs, gold source dot."""
    c = (128, 178)
    return [stroke(arc(*c, r, -45, 45)) for r in (36, 70, 104)] + [fill(circle(*c, 13), GOLD)]


def g_bluetooth():
    """Bluetooth rune, gold pairing dots."""
    rune = line((92, 98), (164, 158), (128, 192), (128, 64), (164, 98), (92, 158))
    return [stroke(rune), fill(circle(62, 128, 10) + circle(194, 128, 10), GOLD)]


def g_sound():
    """Speaker, gold sound waves."""
    speaker = poly((62, 106), (90, 106), (122, 78), (122, 178), (90, 150), (62, 150))
    waves = arc(130, 128, 30, 52, 128) + arc(130, 128, 60, 48, 132)
    return [stroke(speaker), stroke(waves, GOLD)]


def g_display():
    """Monitor on a stand, gold foot."""
    return [stroke(rr(56, 58, 144, 104, 16)), stroke(line((128, 164), (128, 188))),
            stroke(line((94, 192), (162, 192)), GOLD)]


def g_power():
    """Battery, gold lightning bolt."""
    bolt = poly((132, 100), (104, 134), (126, 134), (118, 160), (150, 122), (128, 122))
    return [stroke(rr(54, 84, 132, 88, 18)), stroke(line((200, 114), (200, 142))),
            solid(bolt, GOLD, 5)]


def g_users():
    """Two people, the one behind in gold."""
    head = circle(106, 100, 26)
    body = "M58 190V182Q58 146 106 146Q154 146 154 182V190"
    return [stroke(circle(166, 90, 20), GOLD), stroke("M162 132Q198 132 200 170V178", GOLD),
            knock(body + "Z", 30), knock(head, 30), stroke(head), stroke(body)]


def g_storage():
    """Two stacked drive units, gold activity light."""
    return [stroke(rr(56, 62, 144, 56, 16)), stroke(rr(56, 138, 144, 56, 16)),
            stroke(line((82, 90), (122, 90))), stroke(line((82, 166), (122, 166))),
            fill(circle(170, 90, 10), GOLD), fill(circle(170, 166, 10))]


def g_palette():
    """Paint palette, one gold paint dot."""
    shape = ("M128 58C88 58 58 90 58 128C58 168 90 198 128 198C142 198 148 190 146 178"
             "C144 166 150 158 162 158H174C189 158 198 147 198 128C198 88 166 58 128 58Z")
    return [stroke(shape), fill(circle(98, 106, 11)), fill(circle(128, 86, 11)),
            fill(circle(162, 100, 11)), fill(circle(98, 150, 13), GOLD)]


def g_privacy():
    """Padlock, gold keyhole."""
    shackle = "M96 118V96Q96 64 128 64Q160 64 160 96V118"
    keyhole = circle(128, 148, 11) + "M122 152L118 176H138L134 152Z"
    return [stroke(shackle), stroke(rr(72, 118, 112, 82, 18)), solid(keyhole, GOLD, 3)]


def g_mouse():
    """Mouse, gold scroll wheel."""
    return [stroke(rr(84, 52, 88, 152, 44)), stroke(line((84, 114), (172, 114))),
            stroke(line((128, 76), (128, 92)), GOLD, 16)]


def g_update():
    """Two circling arrows around a gold download arrow."""
    c, r = (128, 128), 62
    top = arc(*c, r, 286, 64) + arrowhead(polar(*c, r, 64), arc_tangent(64), 20)
    bottom = arc(*c, r, 106, 244) + arrowhead(polar(*c, r, 244), arc_tangent(244), 20)
    down = line((128, 102), (128, 152)) + line((110, 136), (128, 154), (146, 136))
    return [stroke(top), stroke(bottom), stroke(down, GOLD, 13)]


def g_calendar():
    """Calendar page with binder rings and days, one gold day."""
    cells = []
    for i, x in enumerate((92, 128, 164)):
        for j, y in enumerate((132, 166)):
            cells.append(fill(rr(x - 10, y - 10, 20, 20, 5), GOLD if (i, j) == (2, 1) else SILVER))
    return [stroke(rr(56, 64, 144, 132, 20)), stroke(line((56, 100), (200, 100))),
            stroke(line((96, 50), (96, 76))), stroke(line((160, 50), (160, 76)))] + cells


def g_clock():
    """Clock face, gold minute hand."""
    return [stroke(circle(128, 128, 68)), stroke(line((128, 128), (128, 88))),
            stroke(line((128, 128), (162, 148)), GOLD)]


def g_media():
    """Ring, gold play triangle."""
    return [stroke(circle(128, 128, 68)), solid(poly((114, 98), (162, 128), (114, 158)), GOLD, 10)]


def g_camera():
    """Camera body with lens ring, gold lens centre."""
    body = ("M56 106Q56 88 74 88H92L104 70H152L164 88H182Q200 88 200 106V170"
            "Q200 188 182 188H74Q56 188 56 170Z")
    return [stroke(body), stroke(circle(128, 138, 30)), fill(circle(128, 138, 13), GOLD)]


def g_bell():
    """Bell, gold clapper."""
    bell = "M78 166Q92 154 92 128V120Q92 84 128 84Q164 84 164 120V128Q164 154 178 166Z"
    return [stroke(line((128, 66), (128, 84))), stroke(bell),
            solid("M110 182A18 18 0 0 0 146 182Z", GOLD, 6)]


def g_accessibility():
    """Ring, gold figure with outstretched arms."""
    figure = [line((88, 112), (128, 122), (168, 112)), line((128, 122), (128, 150)),
              line((106, 186), (128, 150), (150, 186))]
    return ([stroke(circle(128, 128, 70))] + [stroke(d, GOLD, 13) for d in figure] +
            [fill(circle(128, 88, 13), GOLD)])


def g_keyboard():
    """Keyboard with two key rows, gold space bar."""
    keys = [fill(rr(x - 7, 102, 14, 14, 3)) for x in (80, 104, 128, 152, 176)]
    keys += [fill(rr(x - 7, 126, 14, 14, 3)) for x in (92, 116, 140, 164)]
    return ([stroke(rr(50, 78, 156, 100, 18))] + keys +
            [stroke(line((98, 156), (158, 156)), GOLD, 12)])


def g_locale():
    """Speech bubble, gold letter A (drawn as strokes)."""
    bubble = ("M80 62H176Q196 62 196 82V138Q196 158 176 158H122L92 186V158H80"
              "Q60 158 60 138V82Q60 62 80 62Z")
    letter = line((104, 138), (128, 82), (152, 138)) + line((113, 118), (143, 118))
    return [stroke(bubble), stroke(letter, GOLD, 13)]


def g_firewall():
    """Brick wall, one gold brick."""
    joints = [line((104, 72), (104, 110)), line((152, 72), (152, 110)),
              line((80, 110), (80, 146)), line((104, 146), (104, 184)), line((152, 146), (152, 184))]
    return ([stroke(rr(56, 72, 144, 112, 16)), stroke(line((56, 110), (200, 110))),
             stroke(line((56, 146), (200, 146)))] + [stroke(j) for j in joints] +
            [solid("M128 110H176V146H128Z", GOLD, W)])


def g_font():
    """Letters "Aa" drawn as strokes, the small a in gold."""
    big = line((58, 186), (100, 72), (142, 186)) + line((74, 146), (126, 146))
    small = circle(170, 164, 22) + line((192, 136), (192, 186))
    return [stroke(big), stroke(small, GOLD)]


def g_windows():
    """Two overlapping windows, gold title bar on the front one."""
    front = rr(92, 104, 108, 92, 16)
    return [stroke(rr(56, 60, 108, 92, 16)), stroke(line((56, 86), (164, 86))),
            knock(front, 2 * W + 4), stroke(front), stroke(line((92, 130), (200, 130)), GOLD)]


# --- Boswas family --------------------------------------------------------
def g_logo():
    """The official Boswas OS mark (copied from desktop/branding/boswas-os-mark.svg)."""
    return [mark(58, 40, 140, 176)]


def g_store():
    """Shopping bag, gold handle."""
    bag = poly((70, 100), (186, 100), (176, 200), (80, 200))
    return [stroke(bag), stroke("M102 100V88Q102 62 128 62Q154 62 154 88V100", GOLD)]


def g_compat_manager():
    """Application window, gold gear."""
    cx, cy = 168, 168
    teeth = gear(cx, cy, 8, 40, 29, 10, 15, 22.5)
    return window() + [knock(teeth, 24), solid(teeth, GOLD, 5), fill(circle(cx, cy, 11), TILE)]


def g_device_agent():
    """Laptop, gold heartbeat on the screen."""
    pulse = line((86, 108), (104, 108), (114, 86), (130, 128), (142, 96), (150, 108), (170, 108))
    return [stroke(rr(68, 60, 120, 88, 14)), stroke(line((50, 176), (206, 176))),
            stroke(pulse, GOLD, 12)]


def g_security():
    """Shield, gold check mark."""
    return [stroke(shield(128, 54, 62, 148)),
            stroke(line((100, 128), (120, 148), (158, 108)), GOLD, 16)]


def g_control():
    """Three sliders, the middle knob gold."""
    out = [stroke(line((x, 62), (x, 194))) for x in (88, 128, 168)]
    for x, y, paint in ((88, 150, SILVER), (128, 96, GOLD), (168, 128, SILVER)):
        out += [knock(circle(x, y, 18), 14), solid(circle(x, y, 18), paint, 2)]
    return out


def g_update_center():
    """Circling arrow around a gold dot (the ring and dot of the mark)."""
    c, r = (128, 128), 64
    body = arc(*c, r, 40, 330) + arrowhead(polar(*c, r, 330), arc_tangent(330), 24)
    return [stroke(body), fill(circle(*c, 24), GOLD)]


def g_software():
    """Grid of application tiles, one a gold disc."""
    return [stroke(rr(62, 62, 54, 54, 15)), stroke(rr(140, 62, 54, 54, 15)),
            stroke(rr(62, 140, 54, 54, 15)), fill(circle(167, 167, 30), GOLD)]


def g_install():
    """The official mark with a gold download badge."""
    arrow = line((176, 148), (176, 194)) + line((158, 176), (176, 194), (194, 176))
    return [mark(40, 34, 116, 146), knock(circle(176, 176, 40), 20),
            fill(circle(176, 176, 40), GOLD), stroke(arrow, NAVY_900, 12)]


# --- Windows compatibility ------------------------------------------------
def g_win_app():
    """Application window, gold sandbox shield."""
    s = shield(170, 128, 36, 84)
    return window() + [knock(s, 26), solid(s, GOLD, 6)]


def g_win_installer():
    """Application window, gold badge with a download arrow."""
    cx, cy = BADGE
    arrow = line((cx, cy - 20), (cx, cy + 18)) + line((cx - 15, cy + 4), (cx, cy + 19), (cx + 15, cy + 4))
    return window() + badge_disc([stroke(arrow, NAVY_900, 10)])


def g_wine():
    """Application window, gold badge with a run (play) triangle."""
    cx, cy = BADGE
    tri = poly((cx - 10, cy - 18), (cx + 18, cy), (cx - 10, cy + 18))
    return window() + badge_disc([solid(tri, NAVY_900, 6)])


def g_compat_status():
    """Application window, gold badge with a check mark."""
    cx, cy = BADGE
    check = line((cx - 17, cy + 1), (cx - 5, cy + 13), (cx + 18, cy - 12))
    return window() + badge_disc([stroke(check, NAVY_900, 11)])


def g_repair():
    """Application window, gold wrench."""
    head = (136, 136)
    jaw = arc(*head, 20, 0, 270)
    handle = line(polar(*head, 20, 135), (198, 198))
    return window() + [knock(jaw + handle, 44), stroke(jaw, GOLD, 18), stroke(handle, GOLD, 20)]


def g_sandbox():
    """Shield enclosing a gold application window."""
    return [stroke(shield(128, 50, 66, 156)),
            stroke(rr(96, 96, 64, 54, 10), GOLD, 12), stroke(line((96, 114), (160, 114)), GOLD, 12)]


def g_app_policy():
    """Clipboard holding an application window, gold clip."""
    board = "M100 70H82Q68 70 68 84V188Q68 202 82 202H174Q188 202 188 188V84Q188 70 174 70H156"
    return [stroke(board), stroke(rr(92, 112, 72, 60, 10)), stroke(line((92, 132), (164, 132))),
            solid(rr(102, 54, 52, 28, 10), GOLD, 4)]


# --- Mimetypes (light page, navy glyph, gold accent) ------------------------
PAGE = "M70 24H156L200 68V218Q200 232 186 232H70Q56 232 56 218V38Q56 24 70 24Z"
FOLD = "M156 24V56Q156 68 168 68H200Z"


def page_window(accent: list[str]) -> list[str]:
    """The application-window glyph in navy on the page, plus an accent."""
    return [stroke(rr(78, 96, 100, 84, 14), INK, 12), stroke(line((78, 120), (178, 120)), INK, 12)] + accent


def g_mime_exe():
    """Page with an application window and a gold sandbox shield."""
    s = shield(170, 150, 28, 64)
    return page_window([knock(s, 20, PAGE_PAINT), solid(s, GOLD, 5)])


def g_mime_msi():
    """Page with an application window and a gold download badge."""
    cx, cy, r = 170, 178, 30
    arrow = line((cx, cy - 16), (cx, cy + 14)) + line((cx - 12, cy + 2), (cx, cy + 15), (cx + 12, cy + 2))
    return page_window([knock(circle(cx, cy, r), 14, PAGE_PAINT), fill(circle(cx, cy, r), GOLD),
                        stroke(arrow, NAVY_900, 9)])


def g_mime_lnk():
    """Page with an application window and a gold shortcut-arrow badge."""
    box = rr(62, 156, 52, 52, 12)
    curve = "M76 194V184Q76 170 92 170H100" + arrowhead((102, 170), (1, 0), 10, 45)
    return page_window([knock(box, 12, PAGE_PAINT), solid(box, GOLD, 4), stroke(curve, NAVY_900, 8)])


# ---------------------------------------------------------------------------
# The icon list: (file name, title, glyph, context directory, aliases).
# Aliases are written as real files (same drawing, own id prefix).
# ---------------------------------------------------------------------------
APPS = "apps"
MIME = "mimetypes"

ICONS = [
    # Applications in the image
    ("preferences-system", "Settings", g_settings, APPS, ("systemsettings",)),
    ("hwinfo", "System Information", g_info, APPS, ()),
    ("utilities-terminal", "Terminal", g_terminal, APPS, ("org.kde.konsole",)),
    ("system-file-manager", "File Manager", g_files, APPS, ("org.kde.dolphin",)),
    ("utilities-system-monitor", "System Monitor", g_monitor, APPS, ("org.kde.plasma-systemmonitor",)),
    ("web-browser", "Web Browser", g_browser, APPS, ("firefox-esr", "konqueror")),
    ("accessories-calculator", "Calculator", g_calculator, APPS, ("org.kde.kcalc",)),
    ("accessories-text-editor", "Text Editor", g_editor, APPS,
     ("kwrite", "org.kde.kwrite", "kate", "org.kde.kate", "gvim")),
    ("gwenview", "Image Viewer", g_image, APPS, ("org.kde.gwenview", "preferences-desktop-wallpaper")),
    ("okular", "Document Viewer", g_book, APPS, ("org.kde.okular",)),
    ("utilities-file-archiver", "Archive Manager", g_archive, APPS, ("ark", "org.kde.ark")),
    ("spectacle", "Screenshot", g_screenshot, APPS, ("org.kde.spectacle",)),
    ("help-browser", "Help", g_help, APPS, ("org.kde.khelpcenter",)),
    ("kfind", "Find Files", g_find, APPS, ()),
    ("kwalletmanager", "Wallet", g_wallet, APPS, ()),
    ("partitionmanager", "Partition Manager", g_partition, APPS, ()),
    ("kmenuedit", "Menu Editor", g_menuedit, APPS, ()),
    ("htop", "Process Viewer", g_htop, APPS, ()),
    ("tools-report-bug", "Report a Bug", g_bug, APPS, ()),
    ("preferences-desktop-emoticons", "Emoji", g_emoji, APPS, ()),
    # System categories (Boswas Control Center, KDE System Settings)
    ("preferences-system-network", "Network", g_network, APPS, ()),
    ("preferences-system-bluetooth", "Bluetooth", g_bluetooth, APPS, ()),
    ("preferences-desktop-sound", "Audio", g_sound, APPS, ()),
    ("preferences-desktop-display", "Display", g_display, APPS, ("preferences-desktop-display-randr",)),
    ("preferences-system-power-management", "Power", g_power, APPS, ()),
    ("preferences-system-users", "Users", g_users, APPS, ("system-users",)),
    ("boswas-storage", "Storage", g_storage, APPS, ()),
    ("preferences-desktop-theme-global", "Personalization", g_palette, APPS, ()),
    ("preferences-system-privacy", "Privacy", g_privacy, APPS, ("preferences-desktop-user-password",)),
    ("preferences-desktop-peripherals", "Devices", g_mouse, APPS, ("preferences-desktop-mouse",)),
    ("system-software-update", "Updates", g_update, APPS, ()),
    ("preferences-desktop-notification-bell", "Notifications", g_bell, APPS, ()),
    ("preferences-desktop-accessibility", "Accessibility", g_accessibility, APPS, ()),
    ("preferences-desktop-keyboard", "Keyboard", g_keyboard, APPS, ()),
    ("preferences-desktop-locale", "Language and Region", g_locale, APPS, ()),
    ("preferences-security-firewall", "Firewall", g_firewall, APPS, ()),
    ("preferences-desktop-font", "Fonts", g_font, APPS, ()),
    ("preferences-system-windows", "Window Management", g_windows, APPS,
     ("preferences-system-windows-actions",)),
    # Generic applications
    ("office-calendar", "Calendar", g_calendar, APPS, ("x-office-calendar",)),
    ("preferences-system-time", "Clock", g_clock, APPS, ()),
    ("multimedia-player", "Media Player", g_media, APPS, ("applications-multimedia",)),
    ("camera-photo", "Camera", g_camera, APPS, ()),
    # Boswas family
    ("boswas-logo", "Boswas OS", g_logo, APPS,
     ("boswas-os", "start-here", "start-here-kde", "start-here-kde-plasma", "distributor-logo")),
    ("boswas-store", "Boswas Store", g_store, APPS, ()),
    ("boswas-compat-manager", "Compatibility Manager", g_compat_manager, APPS, ()),
    ("boswas-device-agent", "Device Agent", g_device_agent, APPS, ()),
    ("boswas-security-center", "Security Center", g_security, APPS, ()),
    ("boswas-control-center", "Control Center", g_control, APPS, ()),
    ("boswas-update-center", "Update Center", g_update_center, APPS, ()),
    ("boswas-software-center", "Software Center", g_software, APPS, ()),
    ("boswas-install", "Install Boswas OS", g_install, APPS, ()),
    # Windows compatibility
    ("boswas-windows-application", "Windows Application", g_win_app, APPS, ()),
    ("boswas-windows-installer", "Windows Installer", g_win_installer, APPS, ()),
    ("wine", "Windows Program Loader", g_wine, APPS, ("wine-stable",)),
    ("boswas-compat-status", "Compatibility Status", g_compat_status, APPS, ()),
    ("boswas-repair", "Repair Application", g_repair, APPS, ()),
    ("boswas-sandbox", "Application Sandbox", g_sandbox, APPS, ()),
    ("boswas-app-policy", "Application Policy", g_app_policy, APPS, ()),
    # Mimetypes. shared-mime-info names .exe/.dll files
    # application/vnd.microsoft.portable-executable (a subclass of
    # application/x-msdownload, whose alias is x-ms-dos-executable), so the
    # program page is installed under all of those names.
    ("application-x-ms-dos-executable", "Windows Program", g_mime_exe, MIME,
     ("application-x-msdownload", "application-vnd.microsoft.portable-executable",
      "application-x-ms-ne-executable")),
    ("application-x-msi", "Windows Installer Package", g_mime_msi, MIME, ()),
    ("application-x-ms-shortcut", "Windows Shortcut", g_mime_lnk, MIME, ()),
]


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------
def id_prefix(file_name: str) -> str:
    """Id prefix for a file: its name with anything but [A-Za-z0-9-] as '-'."""
    return re.sub(r"[^A-Za-z0-9-]", "-", file_name)


def gradient_def(prefix: str, name: str) -> str:
    if name in MARK_GRADIENTS:
        attrs, stops = load_mark()["gradients"][MARK_GRADIENTS[name]]
    else:
        attrs, stops = GRADIENTS[name]
        attrs = dict(attrs, gradientUnits="userSpaceOnUse")
    attr_text = " ".join(f'{k}="{v}"' for k, v in sorted(attrs.items()))
    out = [f'    <linearGradient id="{prefix}-{name}" {attr_text}>']
    for offset, colour, opacity in stops:
        op = f' stop-opacity="{opacity}"' if opacity != 1 else ""
        out.append(f'      <stop offset="{offset}" stop-color="{colour}"{op}/>')
    out.append("    </linearGradient>")
    return "\n".join(out)


def background(kind: str) -> list[str]:
    if kind == APPS:
        return ['<rect x="8" y="8" width="240" height="240" rx="56" ry="56" fill="$tile"/>',
                '<rect x="9.5" y="9.5" width="237" height="237" rx="54.5" ry="54.5" '
                'fill="none" stroke="$edge" stroke-width="3"/>']
    return [f'<path d="{PAGE}" fill="$page" stroke="#3C485C" stroke-opacity="0.45" stroke-width="3"/>',
            f'<path d="{FOLD}" fill="$fold"/>']


def render(file_name: str, title: str, glyph, kind: str) -> str:
    prefix = id_prefix(file_name)
    body = "\n".join("  " + text for el in background(kind) + glyph() for text in el.split("\n"))
    order = list(GRADIENTS) + list(MARK_GRADIENTS)
    used = sorted(set(re.findall(r"\$([a-z]+)", body)), key=order.index)
    body = re.sub(r"\$([a-z]+)", lambda m: f"url(#{prefix}-{m.group(1)})", body)
    defs = "\n".join(gradient_def(prefix, name) for name in used)
    return ('<?xml version="1.0" encoding="UTF-8"?>\n'
            '<svg xmlns="http://www.w3.org/2000/svg" width="256" height="256" viewBox="0 0 256 256">\n'
            f"  <title>{title}</title>\n"
            f"  <!-- {HEADER} -->\n"
            f"  <defs>\n{defs}\n  </defs>\n"
            f"{body}\n"
            "</svg>\n")


def all_files():
    """Yield (context, file name, design name, title, glyph) for every file."""
    for name, title, glyph, kind, aliases in ICONS:
        for file_name in (name,) + tuple(aliases):
            yield kind, file_name, name, title, glyph


def build(output: Path) -> list[Path]:
    """Write every icon under output/scalable/; remove stale SVGs there."""
    written = []
    for kind, file_name, _design, title, glyph in all_files():
        target = output / "scalable" / kind / f"{file_name}.svg"
        target.parent.mkdir(parents=True, exist_ok=True)
        data = render(file_name, title, glyph, kind).encode("utf-8")
        if not target.exists() or target.read_bytes() != data:
            target.write_bytes(data)
        written.append(target)
    keep = set(written)
    for kind in (APPS, MIME):
        for stale in sorted((output / "scalable" / kind).glob("*.svg")):
            if stale not in keep:
                stale.unlink()
    return written


def table() -> str:
    """Markdown table of every design, its glyph and its theme names."""
    rows = ["| Design | Glyph | Theme icon names |", "|---|---|---|"]
    for name, title, glyph, kind, aliases in ICONS:
        names = ", ".join(f"`{x}`" for x in (name,) + tuple(aliases))
        where = " (mimetype)" if kind == MIME else ""
        rows.append(f"| {title}{where} | {glyph.__doc__.strip()} | {names} |")
    return "\n".join(rows)


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description="Generate the Boswas icon theme.")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT,
                        help="theme directory to write (default: desktop/icons/Boswas)")
    parser.add_argument("--table", action="store_true", help="print the README name table")
    args = parser.parse_args(argv)
    if args.table:
        print(table())
        return 0
    files = build(args.output)
    print(f"{len(ICONS)} designs, {len(files)} files written to {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
