"""Tests for the Boswas icon theme (desktop/icons).

Run from desktop/icons:  python3 -B -m unittest discover -s tests -v
Standard library only. The install test needs a POSIX sh and install(1).
"""

from __future__ import annotations

import configparser
import os
import re
import shutil
import stat
import subprocess
import sys
import tempfile
import unittest
import xml.etree.ElementTree as ET
from pathlib import Path

ICONS = Path(__file__).resolve().parent.parent
REPO = ICONS.parent.parent
THEME = ICONS / "Boswas"
LIGHT = ICONS / "Boswas-Light"
GENERATOR = ICONS / "tools" / "build_icons.py"
SVG_NS = "{http://www.w3.org/2000/svg}"
HEADER = "Generated by desktop/icons/tools/build_icons.py; do not edit by hand."

# Icon names the image and the Boswas components rely on. Kept here, not
# taken from the generator, so that dropping an icon there fails a test.
REQUIRED_APPS = """
preferences-system systemsettings hwinfo utilities-terminal org.kde.konsole
org.kde.dolphin system-file-manager utilities-system-monitor org.kde.plasma-systemmonitor
firefox-esr web-browser konqueror accessories-calculator org.kde.kcalc
kwrite org.kde.kwrite accessories-text-editor kate org.kde.kate gvim
gwenview org.kde.gwenview okular org.kde.okular ark org.kde.ark utilities-file-archiver
spectacle org.kde.spectacle help-browser org.kde.khelpcenter
kfind kwalletmanager partitionmanager kmenuedit htop tools-report-bug preferences-desktop-emoticons
preferences-system-network preferences-system-bluetooth preferences-desktop-sound
preferences-desktop-display preferences-system-power-management preferences-system-users
system-users boswas-storage preferences-desktop-theme-global preferences-system-privacy
preferences-desktop-peripherals system-software-update
office-calendar x-office-calendar preferences-system-time multimedia-player
applications-multimedia camera-photo
boswas-logo boswas-os start-here start-here-kde start-here-kde-plasma distributor-logo
boswas-store boswas-compat-manager boswas-device-agent boswas-security-center
boswas-control-center boswas-update-center boswas-software-center boswas-install
boswas-windows-application boswas-windows-installer wine boswas-compat-status
boswas-repair boswas-sandbox boswas-app-policy
""".split()
REQUIRED_MIME = """
application-x-ms-dos-executable application-x-msdownload application-x-msi
application-x-ms-shortcut application-vnd.microsoft.portable-executable
""".split()

# desktop/branding/README.md palette, plus #6E7A8F, the dark end of the glyph
# silver. Any other colour (and the retired teal in particular) fails.
PALETTE = {
    "#090F1B", "#0B1220", "#111A2B", "#162034", "#080C16",
    "#FBD693", "#EBC786", "#D9B26E", "#B5935C",
    "#D4DDEC", "#AEB7C7", "#6E7A8F", "#3C485C", "#E8EEF6", "#A8B3C7",
}
# The retired teal accent, as hex and as RGB triplets. Assembled from parts so
# that this file does not match the repository-wide teal check itself.
TEAL = re.compile("|".join(["#17C6" + "C0", "#2ED3" + "CD", r"23,\s*198,\s*" + "192",
                            r"46,\s*211,\s*" + "205"]), re.I)
# Elements that are unsafe, or that Qt's SVG renderer (KDE icons) ignores.
FORBIDDEN_ELEMENTS = {"image", "script", "text", "foreignObject", "style", "mask",
                      "clipPath", "filter", "pattern", "use", "svg"}


def svg_files(root: Path = THEME) -> list[Path]:
    return sorted((root / "scalable").glob("*/*.svg"))


def id_prefix(stem: str) -> str:
    return re.sub(r"[^A-Za-z0-9-]", "-", stem) + "-"


def read_theme(path: Path) -> configparser.ConfigParser:
    parser = configparser.ConfigParser(interpolation=None)
    parser.optionxform = str
    parser.read(path, encoding="utf-8")
    return parser


class SourceTree(unittest.TestCase):
    def test_required_icons_exist(self):
        for name in REQUIRED_APPS:
            self.assertTrue((THEME / "scalable/apps" / f"{name}.svg").is_file(), name)
        for name in REQUIRED_MIME:
            self.assertTrue((THEME / "scalable/mimetypes" / f"{name}.svg").is_file(), name)

    def test_only_svg_icons(self):
        for path in (THEME / "scalable").rglob("*"):
            if path.is_file():
                self.assertEqual(path.suffix, ".svg", path)
                self.assertFalse(path.is_symlink(), path)

    def test_light_theme_has_index_only(self):
        # Boswas-Light gets its icons from install.sh, copied from Boswas.
        self.assertEqual(sorted(p.name for p in LIGHT.iterdir()), ["index.theme"])

    def test_text_files_are_lf_utf8(self):
        for path in ICONS.rglob("*"):
            if path.is_file() and "__pycache__" not in path.parts:
                data = path.read_bytes()
                self.assertNotIn(b"\r", data, path)
                data.decode("utf-8")

    def test_readme_lists_every_icon(self):
        readme = (ICONS / "README.md").read_text(encoding="utf-8")
        for path in svg_files():
            self.assertIn(f"`{path.stem}`", readme, path.stem)
        table = subprocess.run([sys.executable, "-B", str(GENERATOR), "--table"], check=True,
                               capture_output=True, text=True).stdout
        self.assertIn(f"<!-- BEGIN ICON TABLE -->\n{table}<!-- END ICON TABLE -->", readme,
                      "README table is stale: paste the output of build_icons.py --table")


class SvgFiles(unittest.TestCase):
    def test_structure(self):
        files = svg_files()
        self.assertGreater(len(files), 60)
        for path in files:
            with self.subTest(icon=path.name):
                text = path.read_text(encoding="utf-8")
                self.assertTrue(text.startswith('<?xml version="1.0" encoding="UTF-8"?>\n'))
                self.assertIn(HEADER, text)
                root = ET.fromstring(text)
                self.assertEqual(root.tag, f"{SVG_NS}svg")
                self.assertEqual(root.get("viewBox"), "0 0 256 256")
                self.assertEqual((root.get("width"), root.get("height")), ("256", "256"))
                self.assertIsNotNone(root.find(f"{SVG_NS}title"))

    def test_self_contained_and_qt_safe(self):
        for path in svg_files():
            with self.subTest(icon=path.name):
                text = path.read_text(encoding="utf-8")
                root = ET.fromstring(text)
                for el in root.iter():
                    tag = el.tag.replace(SVG_NS, "")
                    self.assertFalse(el is not root and tag in FORBIDDEN_ELEMENTS, tag)
                    self.assertTrue(el.tag.startswith(SVG_NS), el.tag)
                    for attr, value in el.attrib.items():
                        local = attr.split("}")[-1]
                        self.assertFalse(local.lower().startswith("on"), attr)
                        if local == "href":
                            self.assertTrue(value.startswith("#"), value)
                        for ref in re.findall(r"url\(([^)]*)\)", value):
                            self.assertTrue(ref.startswith("#"), ref)
                for word in ("<image", "<script", "<text", "<!entity", "javascript:"):
                    self.assertNotIn(word, text.lower())

    def test_no_teal_and_palette_only(self):
        for path in svg_files():
            with self.subTest(icon=path.name):
                text = path.read_text(encoding="utf-8")
                self.assertIsNone(TEAL.search(text))
                colours = {c.upper() for c in re.findall(r"#[0-9A-Fa-f]{6}\b", text)}
                self.assertLessEqual(colours, PALETTE, colours - PALETTE)

    def test_ids_unique_prefixed_and_resolved(self):
        seen = {}
        for path in svg_files():
            with self.subTest(icon=path.name):
                text = path.read_text(encoding="utf-8")
                root = ET.fromstring(text)
                ids = [el.get("id") for el in root.iter() if el.get("id")]
                self.assertEqual(len(ids), len(set(ids)), "duplicate id")
                for ident in ids:
                    self.assertTrue(ident.startswith(id_prefix(path.stem)), ident)
                    self.assertNotIn(ident, seen, f"also in {seen.get(ident)}")
                    seen[ident] = path.name
                refs = set(re.findall(r"url\(#([^)]+)\)", text)) | set(re.findall(r'href="#([^"]+)"', text))
                self.assertLessEqual(refs, set(ids), refs - set(ids))

    def test_logo_uses_the_official_mark(self):
        mark = ET.parse(REPO / "desktop/branding/boswas-os-mark.svg").getroot()
        paths = [p.get("d") for p in mark.iter(f"{SVG_NS}path")]
        self.assertEqual(len(paths), 2)
        for name in ("boswas-logo", "start-here-kde-plasma", "boswas-install"):
            text = (THEME / "scalable/apps" / f"{name}.svg").read_text(encoding="utf-8")
            for d in paths:
                self.assertIn(f'd="{d}"', text, name)

    def test_aliases_repeat_their_design(self):
        # Files with the same title are one design; apart from the id prefix
        # they must be identical.
        groups = {}
        for path in svg_files():
            text = path.read_text(encoding="utf-8")
            title = ET.fromstring(text).find(f"{SVG_NS}title").text
            groups.setdefault((path.parent.name, title), []).append(
                text.replace(id_prefix(path.stem), "ID-"))
        self.assertGreaterEqual(len(groups), 60)
        for key, texts in groups.items():
            self.assertEqual(len(set(texts)), 1, key)


class ThemeIndex(unittest.TestCase):
    def check_index(self, path: Path, name: str, inherits: str):
        theme = read_theme(path)
        head = theme["Icon Theme"]
        self.assertEqual(head["Name"], name)
        self.assertTrue(head.get("Comment"))
        self.assertEqual(head["Inherits"], inherits)
        directories = head["Directories"].split(",")
        self.assertEqual(directories, ["scalable/apps", "scalable/mimetypes"])
        contexts = {"scalable/apps": "Applications", "scalable/mimetypes": "MimeTypes"}
        for directory in directories:
            self.assertIn(directory, theme, directory)
            section = theme[directory]
            self.assertEqual(section["Type"], "Scalable")
            self.assertEqual(section["Context"], contexts[directory])
            size, low, high = (int(section[k]) for k in ("Size", "MinSize", "MaxSize"))
            self.assertEqual((size, low, high), (256, 16, 512))
            self.assertTrue((THEME / directory).is_dir(), directory)
        extra = set(theme.sections()) - {"Icon Theme"} - set(directories)
        self.assertEqual(extra, set())

    def test_dark_theme(self):
        self.check_index(THEME / "index.theme", "Boswas", "breeze-dark,breeze,hicolor")

    def test_light_theme(self):
        self.check_index(LIGHT / "index.theme", "Boswas Light", "breeze,hicolor")


class Generator(unittest.TestCase):
    def test_output_is_up_to_date(self):
        with tempfile.TemporaryDirectory() as tmp:
            subprocess.run([sys.executable, "-B", str(GENERATOR), "--output", tmp],
                           check=True, capture_output=True)
            fresh = {p.relative_to(tmp): p.read_bytes() for p in svg_files(Path(tmp))}
        committed = {p.relative_to(THEME): p.read_bytes() for p in svg_files()}
        self.assertEqual(sorted(fresh), sorted(committed), "icon set differs: re-run build_icons.py")
        stale = [str(k) for k in fresh if fresh[k] != committed[k]]
        self.assertEqual(stale, [], "stale icons: re-run desktop/icons/tools/build_icons.py")


@unittest.skipUnless(shutil.which("sh") and shutil.which("install"), "needs sh and install(1)")
class Install(unittest.TestCase):
    def test_install_both_themes(self):
        with tempfile.TemporaryDirectory() as tmp:
            dest = Path(tmp) / "root"
            subprocess.run(["sh", str(ICONS / "install.sh"), str(dest)], check=True)
            icons = dest / "usr/share/icons"
            self.assertEqual(sorted(p.name for p in dest.iterdir()), ["usr"])
            self.assertEqual(sorted(p.name for p in icons.iterdir()), ["Boswas", "Boswas-Light"])
            for theme in ("Boswas", "Boswas-Light"):
                root = icons / theme
                for name in REQUIRED_APPS:
                    self.assertTrue((root / "scalable/apps" / f"{name}.svg").is_file(), (theme, name))
                for name in REQUIRED_MIME:
                    self.assertTrue((root / "scalable/mimetypes" / f"{name}.svg").is_file(), (theme, name))
                src = THEME if theme == "Boswas" else LIGHT
                self.assertEqual((root / "index.theme").read_bytes(), (src / "index.theme").read_bytes())
            for path in [dest / "usr", dest / "usr/share"] + sorted(icons.rglob("*")) + [icons]:
                mode = stat.S_IMODE(os.lstat(path).st_mode)
                self.assertFalse(path.is_symlink(), path)
                self.assertEqual(mode, 0o755 if path.is_dir() else 0o644, path)
            dark = {p.relative_to(icons / "Boswas"): p.read_bytes() for p in (icons / "Boswas").rglob("*.svg")}
            light = {p.relative_to(icons / "Boswas-Light"): p.read_bytes()
                     for p in (icons / "Boswas-Light").rglob("*.svg")}
            self.assertEqual(dark, light)
            self.assertEqual(len(dark), len(svg_files()))

    def test_usage_error(self):
        result = subprocess.run(["sh", str(ICONS / "install.sh")], capture_output=True)
        self.assertEqual(result.returncode, 2)


if __name__ == "__main__":
    unittest.main()
