# Boswas Classic Konsole profile.
# Generated by desktop/presets/tools/build_presets.py from presets.json; do not edit by hand.

[Appearance]
ColorScheme=BoswasClassic
Font=Hack,11

[General]
Command=/usr/bin/bash --rcfile /usr/share/boswas/terminal/bashrc
Name=Boswas Classic
Parent=FALLBACK/

[Scrolling]
HistorySize=10000

[Terminal Features]
BlinkingCursorEnabled=false
